Enhancements and bug fixes

diff --git a/add_year b/add_year
--- a/add_year
+++ b/add_year
@@ -22,8 +22,6 @@ if [ ! $NCRCAT ] ; then
   fi
 fi
 #
-# Parse filenames as needed
-#
 if [ "$AYEAR" = "2100" ] ; then
   FILE=`ls | egrep "^CAT\." | egrep '\.209001\-209912\.nc$' | head -1`
   FLEN=`echo $FILE | wc -c`
@@ -68,6 +66,60 @@ if [ "$AYEAR" = "2100" ] ; then
         $NCRCAT -O CAT.${c}.${h}.${v}.209001-209912.nc ${c}.${h}.${v}.2100.nc $DF
         if [ $? = 0 ] ; then
           rm -f CAT.${c}.${h}.${v}.209001-209912.nc ${c}.${h}.${v}.2100.nc
+          echo "Concatenated "$DF
+        else
+          echo "Failure on concat of "${DF}
+          exit 1
+        fi
+      done
+    done
+  done
+fi
+#
+if [ "$AYEAR" = "2060" ] ; then
+  FILE=`ls | egrep "^CAT\." | egrep '\.205001\-205912\.nc$' | head -1`
+  FLEN=`echo $FILE | wc -c`
+  NDOT=0
+  CSTR=1
+  while [ $CSTR -le $FLEN ] ; do
+    CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
+    if [ "$CURC" = "." ] ; then
+       NDOT=`expr '(' $NDOT ')' '+' '1'`
+    fi
+    CSTR=`expr '(' $CSTR ')' '+' '1'`
+  done
+  IDOT=1
+  DCAS=1
+  DVAR=1
+  DHT1=1
+  DHT2=1
+  while [ $IDOT -le $NDOT ] ; do
+    CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
+    case "$CURC" in
+      cam2 | clm2 | pop | csim | cice )
+        DCAS=`expr '(' $IDOT ')' '-' '1'`
+        DVAR=`expr '(' $IDOT ')' '+' '1'`
+        DHT1=$IDOT ;;
+    esac
+    IDOT=`expr '(' $IDOT ')' '+' '1'`
+  done
+  DCMP=$DHT1
+  DHT2=`expr '(' $DHT1 ')' '+' '1'`
+  DVAR=`expr '(' $DVAR ')' '+' '1'`
+  DTIM=`expr '(' $DVAR ')' '+' '1'`
+#
+  CASES=`ls | egrep '\.205001\-205912\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
+   VARS=`ls | egrep '\.205001\-205912\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
+   HTAP=`ls | egrep '\.205001\-205912\.nc$' | cut -d"." -f${DHT1},${DHT2} | sort | uniq`
+   COMP=`ls | egrep '\.205001\-205912\.nc$' | cut -d"." -f${DCMP} | sort | uniq`
+#
+  for c in $CASES ; do
+    for h in $HTAP ; do
+      for v in $VARS ; do
+        DF=CAT.${c}.${h}.${v}.205001-206012.nc
+        $NCRCAT -O CAT.${c}.${h}.${v}.205001-205912.nc ${c}.${h}.${v}.2060.nc $DF
+        if [ $? = 0 ] ; then
+          rm -f CAT.${c}.${h}.${v}.205001-205912.nc ${c}.${h}.${v}.2060.nc
           echo "Concatenated "$DF
         else
           echo "Failure on concat of "${DF}
diff --git a/process_cm3_template b/process_cm3_template
--- a/process_cm3_template
+++ b/process_cm3_template
@@ -610,9 +610,11 @@ while [ $YEARNOW -le $YEAREND ] ; do
   fi
   if [ "$HIST" = "pop.h" ] && [ "$TPER" = "mon" ] ; then
     ./concatenate_data D
+    ./store_to_archive &
   fi
   if [ "$HIST" = "cam2.h1" ] && [ "$TPER" = "day" ] ; then
     ./concatenate_data D
+    ./store_to_archive &
   fi
   YEARNOW=`expr $YEARNOW + 1`;export YEARNOW
 done
@@ -621,14 +623,29 @@ done
 #
 echo "Final concatenating of "$CASE"."$HIST" at "`date`
 ./concatenate_data Y
-./concatenate_data A
 if [ $? -eq 0 ] ; then
+  ./concatenate_data A
+  if [ $? -eq 0 ] ; then
+    if [ "$YEAREND" = "2100" ] || [ "$YEAREND" = "2005" ] || [ "$YEAREND" = "2060" ] ; then
+      ./concatenate_data $YEAREND
+      if [ $? -ne 0 ] ; then
+        echo "concatenate_data "${YEAREND}" failed"
+        exit 1
+      fi
+    fi
+  else
+    echo "concatenate_data A failed"
+    exit 1
+  fi
+else
+  echo "concatenate_data Y failed"
+  exit 1
+fi
 #
 # Store completed data on archival system
 #
-    ./store_to_archive
-  else
-    echo "Error from concatenate_data A"
-    exit 1
-  fi
+./store_to_archive
+if [ $? -ne 0 ] ; then
+  echo "store_to_archive failed"
+  exit 1
 fi
diff --git a/process_cm5_template b/process_cm5_template
--- a/process_cm5_template
+++ b/process_cm5_template
@@ -449,9 +449,11 @@ while [ $YEARNOW -le $YEAREND ] ; do
   fi
   if [ "$HIST" = "pop.h" ] && [ "$TPER" = "mon" ] ; then
     ./concatenate_data D
+    ./store_to_archive &
   fi
   if [ "$HIST" = "cam2.h1" ] && [ "$TPER" = "day" ] ; then
     ./concatenate_data D
+    ./store_to_archive &
   fi
 done
 #
@@ -462,20 +464,11 @@ echo "Final concatenating of "$CASE"."$HIST" at "`date`
 if [ $? -eq 0 ] ; then
   ./concatenate_data A
   if [ $? -eq 0 ] ; then
-    if [ "$YEAREND" = "2100" ] || [ "$YEAREND" = "2005" ] ; then
-      if [ "$HIST" = "pop.h" ] && [ "$TPER" = "mon" ] ; then
-        ./concatenate_data $YEAREND
-        if [ $? -ne 0 ] ; then
-          echo "concatenate_data "${YEAREND}" failed"
-          exit 1
-        fi
-      fi
-      if [ "$HIST" = "cam2.h1" ] && [ "$TPER" = "day" ] ; then
-        ./concatenate_data $YEAREND
-        if [ $? -ne 0 ] ; then
-          echo "concatenate_data "${YEAREND}" failed"
-          exit 1
-        fi
+    if [ "$YEAREND" = "2100" ] || [ "$YEAREND" = "2005" ] || [ "$YEAREND" = "2060" ] ; then
+      ./concatenate_data $YEAREND
+      if [ $? -ne 0 ] ; then
+        echo "concatenate_data "${YEAREND}" failed"
+        exit 1
       fi
     fi
   else
diff --git a/var_split b/var_split
--- a/var_split
+++ b/var_split
@@ -37,6 +37,7 @@ if [ ! $NCKS ] ; then
     exit 1
   fi
 fi
+echo $NCKS
 #
 # Parse filename
 #
@@ -51,17 +52,30 @@ while [ $CSTR -le $FLEN ] ; do
   CSTR=`expr '(' $CSTR ')' '+' '1'`
 done
 IDOT=1
+DCAS=1
+DVAR=1
+DHT1=1
+DHT2=1
 DPFX=1
 DSFX=1
 while [ $IDOT -le $NDOT ] ; do
   CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
   case "$CURC" in
     cam2 | clm2 | pop | csim | cice )
+      DCAS=`expr '(' $IDOT ')' '-' '1'`
+      DVAR=`expr '(' $IDOT ')' '+' '1'`
       DPFX=`expr '(' $IDOT ')' '+' '1'`
-      DSFX=`expr '(' $DPFX ')' '+' '1'` ;;
+      DSFX=`expr '(' $DPFX ')' '+' '1'`
+      DHT1=$IDOT ;;
   esac
   IDOT=`expr '(' $IDOT ')' '+' '1'`
 done
+DCMP=$DHT1
+DHT2=`expr '(' $DHT1 ')' '+' '1'`
+DVAR=`expr '(' $DVAR ')' '+' '1'`
+DTIM=`expr '(' $DVAR ')' '+' '1'`
+#
+COMP=`echo $FILE | cut -d"." -f${DCMP}`
 OUTPFX=`echo $FILE | cut -d"." -f1-${DPFX}`
 OUTSFX=`echo $FILE | cut -d"." -f${DSFX}-`
 #
@@ -136,11 +150,17 @@ if [ `echo $FIELDS3D | wc -w` -ne 0 ] ; then
     if [ ! -d ${f}_3d.d ] ; then
       mkdir ${f}_3d.d
     fi
-    OUT=${f}_3d.d/${OUTPFX}.${f}.${OUTSFX}
-    $NCKS -O -v ${HEADER},${f} $FILE $OUT
-    if [ $? -ne 0 ] ; then
-      echo "NCKS -O -v ${HEADER},${f} $FILE $OUT failed"
-      exit 1
+    if [ "$COMP" = "cice" ] ; then
+      OUT=${f}_3d.d/${OUTPFX}.${f}_nh.${OUTSFX}
+      $NCKS -O -d nj,280,383 -v ${HEADER},${f} $FILE $OUT
+      OUT=${f}_3d.d/${OUTPFX}.${f}_sh.${OUTSFX}
+      $NCKS -O -d nj,0,75 -v ${HEADER},${f} $FILE $OUT
+    else
+      OUT=${f}_3d.d/${OUTPFX}.${f}.${OUTSFX}
+      if [ $? -ne 0 ] ; then
+        echo "NCKS -O -v ${HEADER},${f} $FILE $OUT failed"
+        exit 1
+      fi
     fi
   done
 fi
