Fixed hsi in archive_write for tukey

diff --git a/archive_write b/archive_write
--- a/archive_write
+++ b/archive_write
@@ -15,8 +15,16 @@ fi
 #
 # If hsi command exists, use it.
 #
-TEST4HSI=`which hsi 2<&1`
+HSI=`which hsi 2<&1`
 if [ $? -ne 0 ] ; then
+  if [ -f /usr/local/bin/hsi ] ; then
+    HSI=/usr/local/bin/hsi
+  else
+    echo "hsi command not found"
+    ./update_status error archive_write
+    exit 1
+  fi
+else
   echo "hsi command not found"
   ./update_status error archive_write
   exit 1
@@ -25,10 +33,10 @@ fi
 # Use HSI to write files to ARCHIVE_D but directory for each field
 #
 echo "mkdir -p $ARCHIVE_D ; chmod 775 $ARCHIVE_D" > MKDIR
-hsi in MKDIR
+$HSI in MKDIR
 echo ${ARCHIVE_D}" created. Ready." ; rm MKDIR
 echo "cd $ARCHIVE_D ; put -U *nc ; chmod 644 *nc" > PUT
-hsi in PUT
+$HSI in PUT
 if [ $? -eq 0 ] ; then
   echo "Files written to "${ARCHIVE_D}
   rm -f PUT 
