Cleaned up archive_write

diff --git a/archive_write b/archive_write
--- a/archive_write
+++ b/archive_write
@@ -1,5 +1,6 @@
 #!/bin/sh
-# Write a file to a mass store
+#
+# Write file(s) to archival tape
 #
 # Arguments:
 # 1 directory on archival system to write file to
@@ -7,8 +8,7 @@
 if [ $# = 1 ] ; then
   ARCHIVE_D=$1
 else
-  echo "I need an arguments:"
-  echo "Directory on archival system to write file to"
+  echo "archive_write ERROR - missing argument ARCHIVE_D"
   ./update_status error archive_write
   exit 1
 fi
@@ -16,22 +16,24 @@ fi
 # If hsi command exists, use it.
 #
 TEST4HSI=`which hsi 2<&1`
+if [ $? -ne 0 ] ; then
+  echo "hsi command not found"
+  ./update_status error archive_write
+  exit 1
+fi
+#
+# Use HSI to write files to ARCHIVE_D but directory for each field
+#
+echo "mkdir -p $ARCHIVE_D ; chmod 775 $ARCHIVE_D" > MKDIR
+hsi in MKDIR
+echo ${ARCHIVE_D}" created. Ready." ; rm MKDIR
+echo "cd $ARCHIVE_D ; put -U *nc ; chmod 644 *nc" > PUT
+hsi in PUT
 if [ $? -eq 0 ] ; then
-  echo "mkdir -p $ARCHIVE_D ; chmod 775 $ARCHIVE_D" > MKDIR
-  hsi in MKDIR
-  echo ${ARCHIVE_D}" created. Ready." ; rm MKDIR
-  echo "cd $ARCHIVE_D ; put -U *nc ; chmod 644 *nc" > PUT
-  hsi in PUT
-  if [ $? -eq 0 ] ; then
-    echo "Files written to "${ARCHIVE_D}
-    rm -f PUT 
-  else
-    echo "Problem with HPSS on write. Stopping"
-    ./update_status error archive_write
-    exit 1
-  fi
+  echo "Files written to "${ARCHIVE_D}
+  rm -f PUT 
 else
-  echo "Cannot find hsi command."
+  echo "Problem with HPSS on write. Stopping"
   ./update_status error archive_write
   exit 1
 fi
