Hopefully fixed permissions issues on HPSS mkdir commands

diff --git a/archive_write_keep b/archive_write_keep
--- a/archive_write_keep
+++ b/archive_write_keep
@@ -17,29 +17,26 @@ fi
 #
 HSI=`which hsi 2<&1`
 if [ $? -ne 0 ] ; then
-  if [ -f /usr/local/bin/hsi ] ; then
-    HSI=/usr/local/bin/hsi
-  else
-    echo "hsi command not found"
-    ../update_status error archive_write
-    exit 1
-  fi
-else
-  echo "hsi command: "${HSI}
+  echo "hsi command not found"
+  ../update_status error archive_write
+  exit 1
 fi
 #
 # Use HSI to write files to ARCHIVE_D but directory for each field
 #
-echo "mkdir -p $ARCHIVE_D ; chmod 775 $ARCHIVE_D" > MKDIR
-$HSI in MKDIR
-echo ${ARCHIVE_D}" created. Ready." ; rm MKDIR
-echo "cd $ARCHIVE_D ; put -U *nc ; chmod 644 *nc" > PUT
-$HSI in PUT
-if [ $? -eq 0 ] ; then
-  echo "Files written to "${ARCHIVE_D}
-  rm -f PUT 
-else
-  echo "Problem with HPSS on write. Stopping"
-  ../update_status error archive_write
-  exit 1
+$HSI -q "umask 0 ; mkdir -m 7775 -p $ARCHIVE_D"
+if [ $? -ne 0 ] ; then
+  echo "Problem with HPSS on mkdir of "${ARCHIVE_D}". Warning."
+  ../update_status warning archive_write
+  echo ${ARCHIVE_D}" created. Ready."
+  echo "cd $ARCHIVE_D ; put -U *nc ; chmod 644 *nc" > PUT
+  $HSI in PUT
+  if [ $? -eq 0 ] ; then
+    echo "Files written to "${ARCHIVE_D}" and kept on disk."
+    rm -f PUT 
+  else
+    echo "Problem with HPSS on write to "${ARCHIVE_D}". Stopping"
+    ../update_status error archive_write
+    exit 1
+  fi
 fi
