Added LE5 OIC runs

diff --git a/archive_write b/archive_write
--- a/archive_write
+++ b/archive_write
@@ -17,15 +17,9 @@ fi
 #
 HSI=`which hsi 2<&1`
 if [ $? -ne 0 ] ; then
-  if [ -f /usr/local/bin/hsi ] ; then
-    HSI=/usr/local/bin/hsi
-  else
-    echo "hsi command not found"
-    ../update_status error archive_write
-    exit 1
-  fi
-else
-  echo "hsi command: "${HSI}
+  echo "hsi command not found"
+  ../update_status error archive_write
+  exit 1
 fi
 #
 # Use HSI to write files to ARCHIVE_D but directory for each field
