More changes to concatenation

diff --git a/cf_var_year_to_all b/cf_var_year_to_all
--- a/cf_var_year_to_all
+++ b/cf_var_year_to_all
@@ -27,82 +27,51 @@ EXPIDS=`ls | egrep '\.nc$' | cut -d"." -f2 | sort | uniq`
 for m in $MODEL ; do
   for c in $COMP ; do
     for t in $TABLE ; do
-      VARS=`ls *_${t}.*.${m}.${c}.*cat*_c*.nc | cut -d"_" -f1 | uniq`
+      VARS=`ls *_${t}.*.${m}.${c}.????_c*.nc | cut -d"_" -f1 | uniq`
       for v in $VARS ; do
         for e in $EXPIDS ; do
           if [ $YRCOUNT ] ; then
             echo "Concatenating of "${v}"."${t}"."${e}" files and checking year counts: "$YRCOUNT
-            if [ "$t" == "A2" ] ; then
-              NUM=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc | wc -l`
-              if [ $NUM = $YRCOUNT ] ; then
-                F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc | head -1`
-                F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc | tail -1`
-                T1=`echo $F1 | cut -d"." -f5 | cut -c1-10`
-                T2=`echo $F2 | cut -d"." -f5 | cut -c16-25`
-                TS=`date '+%y%m%d'`
-                TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
-                $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc $TF
-                if [ $? -eq 0 ] ; then
-                  rm -f ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc
-                  DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
-                  mv $TF $DF
-                  echo "Completed "$DF
-                fi
+            NUM=`ls ${v}_${t}.${e}.${m}.${c}.????_c*.nc | wc -l`
+            if [ $NUM = $YRCOUNT ] ; then
+              TS=`date '+%y%m%d'`
+              Y1=`ls ${v}_${t}.${e}.${m}.${c}.????_c*.nc | head -1 | cut -d"." -f5`
+              Y2=`ls ${v}_${t}.${e}.${m}.${c}.????_c*.nc | tail -1 | cut -d"." -f5`
+              if [ "$t" == "A2" ] ; then
+                DF=${v}_${t}.${e}.${m}.${c}.${Y1}-01-01_cat_${Y2}-12-31_c${TS}.nc
               else
-               echo "Missing year(s) from "${v}"."${t}"."${e}" files"
-                echo "Count is "$NUM" should be "$YRCOUNT
+                DF=${v}_${t}.${e}.${m}.${c}.${Y1}-01_cat_${Y2}-12_c${TS}.nc
+              fi
+              $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????_c*.nc $DF
+              if [ $? -eq 0 ] ; then
+                rm -f ${v}_${t}.${e}.${m}.${c}.????_c*.nc
+                echo "Completed "$DF
+              else
+                echo "Failure on concat of "${c}"."${p}"."${v}" files"
                 exit 1
               fi
             else
-              NUM=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc | wc -l`
-              if [ $NUM = $YRCOUNT ] ; then
-                F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc | head -1`
-                F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc | tail -1`
-                T1=`echo $F1 | cut -d"." -f5 | cut -c1-7`
-                T2=`echo $F2 | cut -d"." -f5 | cut -c13-19`    
-                TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
-                $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc $TF
-                if [ $? -eq 0 ] ; then
-                  rm -f ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc
-                  DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
-                  mv $TF $DF
-                  echo "Completed "${df}
-                fi
-              else
-                echo "Missing year(s) from "${v}"."${t}"."${e}" files"
-                echo "Count is "$NUM" should be "$YRCOUNT
-                exit 1
-              fi
-            fi
-          fi
-        else
-          echo "Concatenating of "${v}"."${t}"."${e}" files WITHOUT checking counts."
-          if [ "$t" == "A2" ] ; then
-            F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc | head -1`
-            F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc | tail -1`
-            T1=`echo $F1 | cut -d"." -f5 | cut -c1-10`
-            T2=`echo $F2 | cut -d"." -f5 | cut -c16-25`
-            TS=`date '+%y%m%d'`
-            TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
-            $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc $TF
-            if [ $? -eq 0 ] ; then
-              rm -f ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c*.nc
-              DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
-              mv $TF $DF
-              echo "Completed "$DF
+              echo "Missing year(s) from "${v}"."${t}"."${e}" files"
+              echo "Count is "$NUM" should be "$YRCOUNT
+              exit 1
             fi
           else
-            F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc | head -1`
-            F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc | tail -1`
-            T1=`echo $F1 | cut -d"." -f5 | cut -c1-7`
-            T2=`echo $F2 | cut -d"." -f5 | cut -c13-19`    
-            TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
-            $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc $TF
+            echo "Concatenating of "${v}"."${t}"."${e}" files WITHOUT checking year counts"
+            TS=`date '+%y%m%d'`
+            Y1=`ls ${v}_${t}.${e}.${m}.${c}.????_c*.nc | head -1 | cut -d"." -f5`
+            Y2=`ls ${v}_${t}.${e}.${m}.${c}.????_c*.nc | tail -1 | cut -d"." -f5`
+            if [ "$t" == "A2" ] ; then
+              DF=${v}_${t}.${e}.${m}.${c}.${Y1}-01-01_cat_${Y2}-12-31_c${TS}.nc
+            else
+              DF=${v}_${t}.${e}.${m}.${c}.${Y1}-01_cat_${Y2}-12_c${TS}.nc
+            fi
+            $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????_c*.nc $DF
             if [ $? -eq 0 ] ; then
-              rm -f ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c*.nc
-              DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
-              mv $TF $DF
-              echo "Completed "${df}
+              rm -f ${v}_${t}.${e}.${m}.${c}.????_c*.nc
+              echo "Completed "$DF
+            else
+              echo "Failure on concat of "${c}"."${p}"."${v}" files"
+              exit 1
             fi
           fi
         fi
diff --git a/var_year_to_all b/var_year_to_all
--- a/var_year_to_all
+++ b/var_year_to_all
@@ -20,94 +20,59 @@ if [ ! $NCRCAT ] ; then
    fi
 fi
 #
-CHEK=`ls b*.*.h*.*.*cat*.nc | cut -d"." -f3 | cut -c1-2 | uniq`
+CHEK=`ls b*.*.h*.*.????.nc | cut -d"." -f3 | cut -c1-2 | uniq`
 for m in $CHEK ; do
   if [ $m = "ES" ] ; then
     FC=3 ; FV=6 ; FT=7 ; FD=4 ; FE=5
   else
     FC=2 ; FV=5 ; FT=6 ; FD=3 ; FE=4
   fi
-  COMP=`ls b*.*.*.h*.*.*cat*.nc | cut -d"." -f${FD}-${FE} | uniq`
+  COMP=`ls b*.*.*.h*.*.????.nc | cut -d"." -f${FD}-${FE} | uniq`
   for p in $COMP ; do
-    VARS=`ls b*.*.${p}.*.*cat*.nc | cut -d"." -f${FV} | uniq`
+    VARS=`ls b*.*.${p}.*.????.nc | cut -d"." -f${FV} | uniq`
     for v in $VARS ; do
-      CASES=`ls b*.${p}.${v}.*cat*.nc | cut -d"." -f1-${FC} | uniq`
+      CASES=`ls b*.${p}.${v}.????.nc | cut -d"." -f1-${FC} | uniq`
       for c in $CASES ; do
         if [ $YRCOUNT ] ; then
           echo "Concatenating of "${c}"."${p}"."${v}" files and checking year counts: "$YRCOUNT
-          if [ $p = "cam2.h1" ] ; then
-            NUM=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | wc -l`
-            if [ $NUM = $YRCOUNT ] ; then
-              Y0=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
-              Y1=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${FT} | cut -c16-19`
-              DF=${c}.${p}.${v}.${Y0}-01-01_allcat_${Y1}-12-31.nc
-              $NCRCAT -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc $DF
-              if [ $? = 0 ] ; then
-                rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
-                TF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
-                mv $DF $TF
-                echo "Completed "$TF
-              else
-                echo "Failure on concat of "${c}"."${p}"."${v}" files"
-                exit 1
-              fi
+          NUM=`ls ${c}.${p}.${v}.????.nc | wc -l`
+          if [ $NUM = $YRCOUNT ] ; then
+            Y0=`ls ${c}.${p}.${v}.????.nc | head -1 | cut -d"." -f${FT}`
+            Y1=`ls ${c}.${p}.${v}.????.nc | tail -1 | cut -d"." -f${FT}`
+            if [ $p = "cam2.h1" ] ; then
+              DF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
             else
-              echo "Missing year(s) from "${c}"."${p}"."${v}" files"
-              echo "Count is "$NUM" should be "$YRCOUNT
+              DF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
+            fi
+            $NCRCAT -O ${c}.${p}.${v}.????.nc $DF
+            if [ $? = 0 ] ; then
+              rm -f ${c}.${p}.${v}.????.nc
+              echo "Completed "$DF
+            else
+              echo "Failure on concat of "${c}"."${p}"."${v}" files"
               exit 1
             fi
           else
-            NUM=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | wc -l`
-            if [ $NUM = $YRCOUNT ] ; then
-              Y0=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
-              Y1=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${FT} | cut -c13-16`
-              DF=${c}.${p}.${v}.${Y0}-01-allcat_${Y1}-12.nc
-              $NCRCAT -O ${c}.${p}.${v}.????-01_cat_????-12.nc $DF
-              if [ $? = 0 ] ; then
-                rm -f ${c}.${p}.${v}.????-01_cat_????-12.nc
-                TF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
-                mv $DF $TF
-                echo "Completed "$TF
-              else
-                echo "Failure on concat of "${c}"."${p}"."${v}" files"
-                exit 1
-              fi
-            else
-              echo "Missing year(s) from "${c}"."${p}"."${v}" files"
-              echo "Count is "$NUM" should be "$YRCOUNT
-              exit 1
-            fi
+            echo "Missing year(s) from "${c}"."${p}"."${v}" files"
+            echo "Count is "$NUM" should be "$YRCOUNT
+            exit 1
           fi
         else
-          echo "Concatenating of "${c}"."${p}"."${v}" files WITHOUT checking counts." 
+          echo "Concatenating of "${c}"."${p}"."${v}" files WITHOUT checking year counts"
+          Y0=`ls ${c}.${p}.${v}.????.nc | head -1 | cut -d"." -f${FT}`
+          Y1=`ls ${c}.${p}.${v}.????.nc | tail -1 | cut -d"." -f${FT}`
           if [ $p = "cam2.h1" ] ; then
-            Y0=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
-            Y1=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${FT} | cut -c16-19`
-            DF=${c}.${p}.${v}.${Y0}-01-01_allcat_${Y1}-12-31.nc
-            $NCRCAT -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc $DF
-            if [ $? = 0 ] ; then
-              rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
-              TF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
-              mv $DF $TF
-              echo "Completed "$TF
-            else
-              echo "Failure on concat of "${c}"."${p}"."${v}" files"
-              exit 1
-            fi
+            DF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
           else
-            Y0=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
-            Y1=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${FT} | cut -c13-16`
-            DF=${c}.${p}.${v}.${Y0}-01_allcat_${Y1}-12.nc
-            $NCRCAT -O ${c}.${p}.${v}.????-01_cat_????-12.nc ${DF}
-            if [ $? = 0 ] ; then
-              rm -f ${c}.${p}.${v}.????-01_cat_????-12.nc
-              TF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
-              mv $DF $TF
-              echo "Completed "$TF
-            else
-              echo "Failure on concat of "${c}"."${p}"."${v}" files"
-              exit 1
-            fi
+            DF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
+          fi
+          $NCRCAT -O ${c}.${p}.${v}.????.nc $DF
+          if [ $? = 0 ] ; then
+            rm -f ${c}.${p}.${v}.????.nc
+            echo "Completed "$DF
+          else
+            echo "Failure on concat of "${c}"."${p}"."${v}" files"
+            exit 1
           fi
         fi
       done
