Tweaks to allow cases with NO CMIP processing applicable

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -26,27 +26,14 @@ if [ $DO_PROC -ne 0 ] ; then
   cd ${PROCDIR}
 fi
 #
-if [ $DO_IPCC -ne 0 ] ; then
-  if [ $CMIP -eq "cm3" ] ; then
-    cd ${PROCDIR}/IPCC
-    ./cm3_var_mon_to_year
-    ./cm3_var_year_to_all
-    if [ $? -eq 0 ] ; then
-      mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
-    else
-      echo "Error from cm3_var_year_to_all"
-      exit 1
-    fi
-  fi
-  if [ $CMIP -eq "cm5" ] ; then
-    cd ${PROCDIR}/CMIP5_data
-    ./cm5_var_mon_to_year
-    ./cm5_var_year_to_all
-    if [ $? -eq 0 ] ; then
-      mv *.${YEARBEG}*${YEAREND}*.nc $CACHEDIR
-    else
-      echo "Error from cm5_var_year_to_all"
-      exit 1
-    fi
+if [ $DO_CMIP -ne 0 ] ; then
+  cd ${PROCDIR}/CMIP
+  ./${CMIP}_var_mon_to_year
+  ./${CMIP}_var_year_to_all
+  if [ $? -eq 0 ] ; then
+    mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
+  else
+    echo "Error from cm3_var_year_to_all"
+    exit 1
   fi
 fi
