Tweaks to for concatenate_datas

diff --git a/concatenate_lme_data b/concatenate_lme_data
--- a/concatenate_lme_data
+++ b/concatenate_lme_data
@@ -12,8 +12,6 @@ fi
 #
 if [ ! $CACHEDIR ] ; then
   echo "No CACHEDIR defined. CAT files stay in subdirs"
-else
-  echo "CACHEDIR: "${CACHEDIR}
 fi
 #
 # Check for ncks
@@ -33,21 +31,23 @@ cd $LOCAL_PROC
 #
 # Process time-variant fields 
 #
-for e in `/bin/ls -d *.d` ; do
-  cd ${LOCAL_PROC}/${e}
-  ../var_lme_year_to_cen
-  if [ $? = 0 ] ; then
-    if [ `/bin/ls | egrep "^CAT\." | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-      for CATFILE in `/bin/ls | egrep "^CAT\." | egrep '\.nc$'` ; do
-        mv $CATFILE $CACHEDIR
-      done
+if [ `/bin/ls -d *.d | wc -l` -ne 0 ] ; then
+  for IDIR in `/bin/ls -d *.d` ; do
+    cd ${LOCAL_PROC}/${IDIR}
+    ../var_lme_year_to_cen
+    if [ $? = 0 ] ; then
+      if [ `/bin/ls | egrep "^CAT\." | egrep '\.nc$' | wc -l` -ne 0 ] ; then
+        for CATFILE in `/bin/ls | egrep "^CAT\." | egrep '\.nc$'` ; do
+          mv $CATFILE $CACHEDIR
+        done
+      fi
+    else
+      echo "Error from var_lme_year_to_cen"
+      echo $CASE" "${HIST}" "${IDIR}
+      ./update_status error concatenate_data
+      exit 1
     fi
-  else
-    echo "Error from var_lme_year_to_cen"
-    echo $CASE" "${HIST}" "${e}
-    ./update_status error concatenate_data
-    exit 1
-  fi
-done
+  done
+fi
 #
 cd ${LOCAL_PROC}
