Tuned up CMIP3 processing

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -114,9 +114,18 @@ fi
 #
 if [ $DO_CMIP -ne 0 ] ; then
   cd ${PROCDIR}/CMIP
-  ./${CMIP}_var_mon_to_year
-  if [ $? -ne 0 ] ; then
-    echo "Error from "${CMIP}"_var_mon_to_year"
-    exit 1
+  if [ "$TCAT" = "Y" ] ; then
+    ./${CMIP}_var_mon_to_year
+    if [ $? -ne 0 ] ; then
+      echo "Error from "${CMIP}"_var_mon_to_year"
+      exit 1
+    fi
+  fi
+  if [ "$TCAT" = "A" ] ; then
+    ./${CMIP}_year_to_all
+    if [ $? -ne 0 ] ; then
+      echo "Error from "${CMIP}"_var_mon_to_year"
+      exit 1
+    fi
   fi
 fi
diff --git a/process_cm3_template b/process_cm3_template
--- a/process_cm3_template
+++ b/process_cm3_template
@@ -626,8 +626,9 @@ if [ $? -eq 0 ] ; then
 #
 # Store completed data on archival system
 #
-  ./store_to_archive
-else
-  echo "Error from concatenate_data A"
-  exit 1
+    ./store_to_archive
+  else
+    echo "Error from concatenate_data A"
+    exit 1
+  fi
 fi
