Major changes - removed all CMIP3 codes and options, hopefully fixed erroneous timesplit and varsplit issues

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -30,90 +30,63 @@ fi
 #
 cd $LOCAL_PROC
 #
-if [ $DO_PROC ] ; then
-  if [ $DO_PROC -ne 0 ] ; then
-    cd ${LOCAL_PROC}
-    if [ "$TCAT" = "M2Y" ] ; then
-      for e in `ls -d *d.d` ; do
-        cd ${LOCAL_PROC}/${e}
-        ../var_mon_to_year
-        if [ $? -ne 0 ] ; then
-          echo "Error from var_mon_to_year"
+if [ "$TCAT" = "M2Y" ] ; then
+  for e in `ls -d *d.d` ; do
+    cd ${LOCAL_PROC}/${e}
+    ../var_mon_to_year
+    if [ $? -ne 0 ] ; then
+      echo "Error from var_mon_to_year"
 	  ./procstat.sh error concatenate_data
-          exit 1
-        fi
-      done
+      exit 1
     fi
-    if [ "$TCAT" = "Y2D" ] ; then
-      for e in `ls -d *4d.d` ; do
-        cd ${LOCAL_PROC}/${e}
-        ../var_year_to_dec
-        if [ $? -ne 0 ] ; then
-          echo "Error from var_year_to_dec"
-          echo $CASE" "${HIST}" "${e}
-	  ./procstat.sh error concatenate_data
-          exit 1
-        else
-          if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-            mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
-          fi
-        fi
-      done
-    fi
-    if [ "$TCAT" = "Y2A" ] ; then
-      for e in `ls -d *d.d` ; do
-        cd ${LOCAL_PROC}/${e}
-        ../var_year_to_all
-        if [ $? -ne 0 ] ; then
-          echo "Error from var_year_to_all"
-          echo $CASE" "${HIST}" "${e}
-	  ./procstat.sh error concatenate_data
-          exit 1
-        else
-          if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-            mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
-          fi
-        fi
-      done
-    fi
-    if [ "$TCAT" = "D2C" ] ; then
-      for e in `ls -d *d.d` ; do
-        cd ${LOCAL_PROC}/${e}
-        ../var_dec_to_cen
-        if [ $? -ne 0 ] ; then
-          echo "Error from var_dec_to_cen"
-          echo $CASE" "${HIST}" "${e}
-	  ./procstat.sh error concatenate_data
-          exit 1
-        else
-          if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-            mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
-          fi
-        fi
-      done
-    fi
-    cd ${LOCAL_PROC}
-  fi
+  done
 fi
-#
-if [ $DO_CMIP ] ; then
-  if [ $DO_CMIP -ne 0 ] ; then
-    cd ${LOCAL_PROC}/CMIP
-    if [ "$TCAT" = "M2Y" ] ; then
-      ./${CMIP}_var_mon_to_year
-      if [ $? -ne 0 ] ; then
-        echo "Error from "${CMIP}"_var_mon_to_year"
-	./procstat.sh error concatenate_data
-        exit 1
+if [ "$TCAT" = "Y2D" ] ; then
+  for e in `ls -d *4d.d` ; do
+    cd ${LOCAL_PROC}/${e}
+    ../var_year_to_dec
+    if [ $? -ne 0 ] ; then
+      echo "Error from var_year_to_dec"
+      echo $CASE" "${HIST}" "${e}
+	  ./procstat.sh error concatenate_data
+      exit 1
+    else
+      if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
+        mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
       fi
     fi
-    if [ "$TCAT" = "Y2A" ] ; then
-      ./${CMIP}_var_year_to_all
-      if [ $? -ne 0 ] ; then
-        echo "Error from "${CMIP}"_var_mon_to_year"
-	./procstat.sh error concatenate_data
-        exit 1
+  done
+fi
+if [ "$TCAT" = "Y2A" ] ; then
+  for e in `ls -d *d.d` ; do
+    cd ${LOCAL_PROC}/${e}
+    ../var_year_to_all
+    if [ $? -ne 0 ] ; then
+      echo "Error from var_year_to_all"
+      echo $CASE" "${HIST}" "${e}
+	  ./procstat.sh error concatenate_data
+      exit 1
+    else
+      if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
+        mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
       fi
     fi
-  fi
+  done
 fi
+if [ "$TCAT" = "D2C" ] ; then
+  for e in `ls -d *d.d` ; do
+    cd ${LOCAL_PROC}/${e}
+    ../var_dec_to_cen
+    if [ $? -ne 0 ] ; then
+      echo "Error from var_dec_to_cen"
+      echo $CASE" "${HIST}" "${e}
+	  ./procstat.sh error concatenate_data
+      exit 1
+    else
+      if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
+        mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
+      fi
+    fi
+  done
+fi
+cd ${LOCAL_PROC}
