Revamped all so that concatenation is done at history level, to years, to cut down on calls to var_split

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -2,91 +2,27 @@
 #
 # Concatenate data as needed by argument
 #
-if [ $# -eq 0 ] ; then
-  echo "Usage: concatenate_data [M2Y|Y2D|Y2A|D2C] (required)"
-  echo " M2Y: concatenate months to years"
-  echo " Y2D: concatenate years to decades"
-  echo " Y2A: concatenate years to all years"
-  echo " D2C: concatenate decades to centuries"
+if [ $# -ne 0 ] ; then
+  echo "Usage: concatenate_data"
   ./procstat.sh error concatenate_data
   exit 1
-fi
-if [ $# -eq 1 ] ; then
-  TCAT=$1
-  if [ "$TCAT" != "M2Y" ] ; then
-    if [ "$TCAT" != "Y2D" ] ; then
-      if [ "$TCAT" != "Y2A" ] ; then
-        if [ "$TCAT" != "D2C" ] ; then
-          echo "Usage: concatenate_data [M2Y|Y2D|Y2A|D2C] (required)"
-          echo " M2Y: concatenate months to years"
-          echo " Y2D: concatenate years to decades"
-          echo " Y2A: concatenate years to all years"
-          echo " D2C: concatenate decades to centuries"
-        fi
-      fi
-    fi
-  fi
 fi
 #
 cd $LOCAL_PROC
 #
-if [ "$TCAT" = "M2Y" ] ; then
-  for e in `ls -d *d.d` ; do
-    cd ${LOCAL_PROC}/${e}
-    ../var_mon_to_year
-    if [ $? -ne 0 ] ; then
-      echo "Error from var_mon_to_year"
-	  ./procstat.sh error concatenate_data
-      exit 1
+for e in `ls -d *d.d` ; do
+  cd ${LOCAL_PROC}/${e}
+  ../var_year_to_all
+  if [ $? -ne 0 ] ; then
+    echo "Error from var_year_to_all"
+    echo $CASE" "${HIST}" "${e}
+    ./procstat.sh error concatenate_data
+    exit 1
+  else
+    if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
+      mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
     fi
-  done
-fi
-if [ "$TCAT" = "Y2D" ] ; then
-  for e in `ls -d *4d.d` ; do
-    cd ${LOCAL_PROC}/${e}
-    ../var_year_to_dec
-    if [ $? -ne 0 ] ; then
-      echo "Error from var_year_to_dec"
-      echo $CASE" "${HIST}" "${e}
-	  ./procstat.sh error concatenate_data
-      exit 1
-    else
-      if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-        mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
-      fi
-    fi
-  done
-fi
-if [ "$TCAT" = "Y2A" ] ; then
-  for e in `ls -d *d.d` ; do
-    cd ${LOCAL_PROC}/${e}
-    ../var_year_to_all
-    if [ $? -ne 0 ] ; then
-      echo "Error from var_year_to_all"
-      echo $CASE" "${HIST}" "${e}
-	  ./procstat.sh error concatenate_data
-      exit 1
-    else
-      if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-        mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
-      fi
-    fi
-  done
-fi
-if [ "$TCAT" = "D2C" ] ; then
-  for e in `ls -d *d.d` ; do
-    cd ${LOCAL_PROC}/${e}
-    ../var_dec_to_cen
-    if [ $? -ne 0 ] ; then
-      echo "Error from var_dec_to_cen"
-      echo $CASE" "${HIST}" "${e}
-	  ./procstat.sh error concatenate_data
-      exit 1
-    else
-      if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
-        mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
-      fi
-    fi
-  done
-fi
+  fi
+done
+#
 cd ${LOCAL_PROC}
diff --git a/process_template b/process_template
--- a/process_template
+++ b/process_template
@@ -243,18 +243,15 @@ case "$TPER" in
     ;;
 esac
 #
-ln -s -f $BASEDIR/archive_list         .
-ln -s -f $BASEDIR/archive_read         .
-ln -s -f $BASEDIR/archive_write        .
-ln -s -f $BASEDIR/var_split        .
-ln -s -f $BASEDIR/var_mon_to_year  .
-ln -s -f $BASEDIR/var_year_to_dec  .
-ln -s -f $BASEDIR/var_year_to_all  .
-ln -s -f $BASEDIR/var_dec_to_cen   .
-ln -s -f $BASEDIR/concatenate_data .
-ln -s -f $BASEDIR/store_to_archive .
-ln -s -f $BASEDIR/annual_averages  .
-ln -s -f $BASEDIR/procstat.sh      .
+ln -s -f $BASEDIR/archive_list      .
+ln -s -f $BASEDIR/archive_read      .
+ln -s -f $BASEDIR/archive_write     .
+ln -s -f $BASEDIR/var_split         .
+ln -s -f $BASEDIR/hist_mon_to_year  .
+ln -s -f $BASEDIR/var_year_to_all   .
+ln -s -f $BASEDIR/concatenate_data  .
+ln -s -f $BASEDIR/store_to_archive  .
+ln -s -f $BASEDIR/procstat.sh       .
 #
 cd $LOCAL_PROC
 #
@@ -275,12 +272,14 @@ if [ ! -f $ARCHIVE_LIST ] ; then
   ./archive_list $ARCHIVE_LIST
 fi
 #
+# Big processing loop
+#
 while [ $YEARNOW -ge $YEARBEG ] ; do
   ./procstat.sh
   YRCHECK=.comp.$CASE.$HIST.$YEARNOW
   if [ -f ${YRCHECK}.nc ] ; then
     touch $YRCHECK
-    rm .????.$CASE.$HIST.${YEARNOW}*.nc
+    rm .????.$CASE.$HIST.????.nc
   else
     if [ `/bin/ls ${YRCHECK}-??.nc | wc -l` -eq 12 ] ; then
       touch $YRCHECK
@@ -364,33 +363,24 @@ while [ $YEARNOW -ge $YEARBEG ] ; do
         done ;;
     esac
 #
-# All time splitting should be done now, ready for var_splitting
+# All time splitting should be done now, ready for concatenation to years and then var_split
 #
     NFNC=`echo $CASE.$HIST.????-??.nc | wc -w`
     if [ ${NFNC} -ne 1 ] ; then
-      for FILE in `/bin/ls $CASE.$HIST.${YEARNOW}-??.nc` ; do
-        ./var_split $FILE erase
-        if [ $? -ne 0 ] ; then
-          echo "Error from var_split on file "$FILE
-          ./procstat.sh error process_template
-          exit 1
-        else
-          touch .proc.$FILE
-        fi
-        if [ -f .proc.$FILE ] ; then
-          touch .comp.$FILE
-          rm -f .proc.$FILE
-        fi
-      done
+      ./hist_mon_to_year
+      if [ $? -ne 0 ] ; then
+        echo "Error from hist_mon_to_year on file "$FILE
+        ./procstat.sh error hist_mon_to_year
+        exit 1
     fi
 #
     NFNC=`echo $CASE.$HIST.????.nc | wc -w`
     if [ ${NFNC} -ne 1 ] ; then
-      for FILE in `/bin/ls $CASE.$HIST.${YEARNOW}.nc` ; do
+      for FILE in `/bin/ls $CASE.$HIST.????.nc` ; do
         ./var_split $FILE erase
         if [ $? -ne 0 ] ; then
           echo "Error from var_split on file "$FILE
-          ./procstat.sh error process_template
+          ./procstat.sh error var_split
           exit 1
         else
           touch .proc.$FILE
@@ -404,19 +394,12 @@ while [ $YEARNOW -ge $YEARBEG ] ; do
 #
     if [ -f ${YRCHECK}.nc ] ; then
       touch $YRCHECK
-      rm .????.$CASE.$HIST.${YEARNOW}*.nc
+      rm .????.$CASE.$HIST.${YEARNOW}.nc
     else
       if [ `/bin/ls .comp.$CASE.$HIST.${YEARNOW}-??.nc | wc -l` -eq 12 ] ; then
         touch $YRCHECK
         rm .????.$CASE.$HIST.${YEARNOW}-??.nc
       fi
-    fi
-#
-# Concatenate all months into respective years, at every year done 
-#
-    echo "Concatenating years at "${YEARNOW}" at "`date`
-    if [ "$TPER" != "ann" ] ; then
-      ./concatenate_data M2Y
     fi
   fi
 #
@@ -433,17 +416,10 @@ while [ $YEARNOW -ge $YEARBEG ] ; do
   export YEARNOW
 done
 #
-# Concatenate months -> years, years -> all (if possible)
+# Concatenate years -> all
 #
 echo "Final concatenating of "$CASE"."$HIST" at "`date`
-./concatenate_data M2Y
-./concatenate_data Y2A
-#
-# Create annual averages of each field (ocean monthly only)
-#
-if [ "$HIST" = "pop.h" ] && [ "$TPER" = "mon" ] ; then
-  ./annual_averages
-fi
+./concatenate_data
 #
 # Store completed data on archival system
 #
