Tweaked concatenate_data

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -15,7 +15,12 @@ if [ $DO_PROC -ne 0 ] ; then
     cd ${PROCDIR}/${e}
     ../var_mon_to_year
     ../var_year_to_all
-    mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
+    if [ $? -eq 0 ] ; then
+      mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
+    else
+      echo "Error from var_year_to_all"
+      exit 1
+    fi
     cd ${PROCDIR}
   done
   cd ${PROCDIR}
@@ -25,7 +30,12 @@ if [ $DO_IPCC -ne 0 ] ; then
   cd ${PROCDIR}/IPCC
   ./cf_var_mon_to_year
   ./cf_var_year_to_all
-  mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
+  if [ $? -eq 0 ] ; then
+    mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
+  else
+    echo "Error from cf_var_year_to_all"
+    exit 1
+  fi
 fi
 cd ${PROCDIR}
 #
