Changes for CMIP5

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -27,13 +27,26 @@ if [ $DO_PROC -ne 0 ] ; then
 fi
 #
 if [ $DO_IPCC -ne 0 ] ; then
-  cd ${PROCDIR}/CMIP5_data
-  ./cf_var_mon_to_year
-  ./cf_var_year_to_all
-  if [ $? -eq 0 ] ; then
-    mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
-  else
-    echo "Error from cf_var_year_to_all"
-    exit 1
+  if [ $TYPE -eq "cm3" ] ; then
+    cd ${PROCDIR}/IPCC
+    ./cm3_var_mon_to_year
+    ./cm3_var_year_to_all
+    if [ $? -eq 0 ] ; then
+      mv *.${YEARBEG}*cat*${YEAREND}*.nc $CACHEDIR
+    else
+      echo "Error from cm3_var_year_to_all"
+      exit 1
+    fi
+  fi
+  if [ $TYPE -eq "cm5" ] ; then
+    cd ${PROCDIR}/CMIP5_data
+    ./cm5_var_mon_to_year
+    ./cm5_var_year_to_all
+    if [ $? -eq 0 ] ; then
+      mv *.${YEARBEG}*${YEAREND}*.nc $CACHEDIR
+    else
+      echo "Error from cm5_var_year_to_all"
+      exit 1
+    fi
   fi
 fi
