Added functionality for trailing single years, like 2005 and 2100, to add to previous chunk of years

diff --git a/concatenate_data b/concatenate_data
--- a/concatenate_data
+++ b/concatenate_data
@@ -3,11 +3,12 @@
 # Concatenate data as needed by argument
 #
 if [ $# -eq 0 ] ; then
-  echo "Usage: concatenate_data [Y|D|5|A] (required)"
+  echo "Usage: concatenate_data [Y|D|5|A|2100|2005] (required)"
   echo " Y: concatenate years     (from months)"
   echo " D: concatenate decades   (from years)"
   echo " 5: concatenate 5-years   (from years)"
   echo " A: concatenate all years (from years)"
+  echo " #: add year # to pre-existing concatenated data"
   exit 1
 fi
 if [ $# -eq 1 ] ; then
@@ -16,13 +17,18 @@ if [ $# -eq 1 ] ; then
     if [ "$TCAT" != "D" ] ; then
       if [ "$TCAT" != "5" ] ; then
         if [ "$TCAT" != "A" ] ; then
-          echo $TCAT" not defined argument"
-          echo "Usage: concatenate_data [Y|D|5|A] (required)"
-          echo " Y: concatenate years     (from months)"
-          echo " D: concatenate decades   (from years)"
-          echo " 5: concatenate 5-years   (from years)"
-          echo " A: concatenate all years (from years)"
-          exit 1
+          if [ "$TCAT" != "2100" ] ; then
+            if [ "$TCAT" != "2005" ] ; then
+              echo $TCAT" not defined argument"
+              echo "Usage: concatenate_data [Y|D|5|A] (required)"
+              echo " Y: concatenate years     (from months)"
+              echo " D: concatenate decades   (from years)"
+              echo " 5: concatenate 5-years   (from years)"
+              echo " A: concatenate all years (from years)"
+              echo " #: add year # to pre-existing concatenated data"
+              exit 1
+            fi
+          fi
         fi
       fi
     fi
@@ -79,6 +85,21 @@ if [ $DO_PROC -ne 0 ] ; then
       ../var_year_to_all
       if [ $? -ne 0 ] ; then
         echo "Error from var_year_to_all"
+        echo $CASE" "${HIST}" "${e}
+        exit 1
+      else
+        if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
+          mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
+        fi
+      fi
+    done
+  fi
+  if [ "$TCAT" = "2100" ] || [ "$TCAT" = "2005" ] ; then
+    for e in `ls -d *d.d` ; do
+      cd ${PROCDIR}/${e}
+      ../add_year $TCAT
+      if [ $? -ne 0 ] ; then
+        echo "Error from add_year "${TCAT}
         echo $CASE" "${HIST}" "${e}
         exit 1
       else
diff --git a/process_cm5_template b/process_cm5_template
--- a/process_cm5_template
+++ b/process_cm5_template
@@ -335,6 +335,7 @@ if [ $DO_PROC -ne 0 ] ; then
   ln -s -f $BASEDIR/var_year_to_dec .
   ln -s -f $BASEDIR/var_year_to_5yr .
   ln -s -f $BASEDIR/var_year_to_all .
+  ln -s -f $BASEDIR/add_year        .
 fi
 #
 ln -s -f $BASEDIR/concatenate_data    .
@@ -461,13 +462,37 @@ done
 #
 echo "Final concatenating of "$CASE"."$HIST" at "`date`
 ./concatenate_data Y
-./concatenate_data A
 if [ $? -eq 0 ] ; then
+  ./concatenate_data A
+  if [ $? -eq 0 ] ; then
+    if [ "$YEAREND" = "2100" ] || [ "$YEAREND" = "2005" ] ; then
+      if [ "$HIST" = "pop.h" ] && [ "$TPER" = "mon" ] ; then
+        ./concatenate_data $YEAREND
+        if [ $? -ne 0 ] ; then
+          echo "concatenate_data "${YEAREND}" failed"
+          exit 1
+        fi
+      fi
+    if [ "$HIST" = "cam2.h1" ] && [ "$TPER" = "day" ] ; then
+       ./concatenate_data $YEAREND
+       if [ $? -ne 0 ] ; then
+         echo "concatenate_data "${YEAREND}" failed"
+         exit 1
+       fi
+    fi
+  else
+    echo "concatenate_data A failed"
+    exit 1
+  fi
+else
+  echo "concatenate_data Y failed"
+  exit 1
+fi
 #
 # Store completed data on archival system
 #
-  ./store_to_archive
-else
-  echo "Error from concatenate_all"
+./store_to_archive
+if [ $? -ne 0 ] ; then
+  echo "store_to_archive failed"
   exit 1
 fi
