Added starts and ends to NE DP experiments

diff --git a/mss_var_read b/mss_var_read
--- a/mss_var_read
+++ b/mss_var_read
@@ -27,12 +27,12 @@ fi
 #
 TEST4HSI=`which hsi 2<&1`
 if [ $? -eq 0 ] ; then
-  hsi -q "cd ${ARCHIVE_PROC} ; cget -u *.${HIST}.{${VARS}}.*.nc"
-  if [ $? -ne 0 ] ; then
-    echo "Error on hsi get of "$ARCHIVE_PROC" files. Stopping."
+  hsi -q "cd ${ARCHIVE_PROC} ; cget -u ${CASE}.${HIST}.{${VARS}}.185001-200512.nc"
+#  if [ $? -ne 0 ] ; then
+#    echo "Error on hsi get of "$ARCHIVE_PROC" files. Stopping."
 #    ./procstat.sh error mss_var_read
-    exit 1
-  fi
+#    exit 1
+#  fi
 else
   echo "Cannot find hsi command."
 #  ./procstat.sh error mss_var_read
