Replaced all scripts with updated scripts from Alice including procstat calls, removed all DCS commands, new experiments

diff --git a/mss_list b/mss_list
--- a/mss_list
+++ b/mss_list
@@ -5,41 +5,28 @@
 #
 if [ $# -ne 1 ] ; then
   echo "Usage: mss_list local_list - REQUIRED"
+  ./procstat.sh error mss_list
   exit 1
 else
   ARCHIVE_L=$1
 fi
 #
-# If NCAR ARCHIVE_ 'msls' command exists, use it.
+# If hsi command exists, use it.
 #
-TEST4MSLS=`which msls 2<&1`
+TEST4HSI=`which hsi 2<&1`
 if [ $? -eq 0 ] ; then
-   rm -f ABCXYZ
-   msls -1 "$ARCHIVE_HIST" >& ABCXYZ
-   if [ $? -eq 0 ] ; then
-     egrep "\.${HIST}\." ABCXYZ >& $ARCHIVE_L
-     rm -f ABCXYZ
-   else
-     echo "Error on mss_list from "$ARCHIVE_HIST
-     exit 1
-   fi
-#
-# If NERSC/ORNL hsi command exists, use it.
-#
-else
-  TEST4HSI=`which hsi 2<&1`
+  rm -f ABCXYZ
+  hsi -q "cd $ARCHIVE_HIST; ls -Fl" >& ABCXYZ
   if [ $? -eq 0 ] ; then
+    egrep "\.${HIST}\." ABCXYZ | cut -c60- >& $ARCHIVE_L
     rm -f ABCXYZ
-    hsi -q "cd $ARCHIVE_HIST; ls -Fl" >& ABCXYZ
-    if [ $? -eq 0 ] ; then
-      egrep "\.${HIST}\." ABCXYZ | cut -c60- >& $ARCHIVE_L
-      rm -f ABCXYZ
-    else
-      echo "Error on mss_list from "$ARCHIVE_HIST
-      exit 1
-    fi
   else
-    echo "Neither msls nor hsi exist."
+    echo "Error on mss_list from "$ARCHIVE_HIST
+    ./procstat.sh error mss_list
     exit 1
   fi
+else
+  echo "Cannot find hsi command."
+  ./procstat.sh error mss_list
+  exit 1
 fi
diff --git a/mss_read b/mss_read
--- a/mss_read
+++ b/mss_read
@@ -5,6 +5,7 @@ if [ $# -ne 2 ] ; then
   echo "Usage: mss_read ARCHIVE_LIST YEARNOW"
   echo "Requires ARCHIVE_LIST and YEARNOW"
   echo "CASE HIST ARCHIVE_HIST must be defined"
+  ./procstat.sh error mss_read
   exit 1
 else
   ARCHIVE_LIST=$1
@@ -13,6 +14,7 @@ fi
 #
 if ! [ -f $ARCHIVE_LIST ] ; then
   echo "mss_read: No "$ARCHIVE_LIST" file found. Exit."
+  ./procstat.sh error mss_read
   exit 1
 fi
 if [ ! $CASE ] ; then
@@ -49,75 +51,39 @@ else
   ARCHIVE_FILES=$CASE.$HIST."{"${LST}"}"
 fi
 #
-# If NCAR ARCHIVE_ msrcp command exists, use it.
-#
-TEST4MSRCP=`which msrcp 2<&1`
-if [ $? -eq 0 ] ; then
-   MSRCP=`which msrcp`
-   $MSRCP -overwrite sizemismatch mss:"$ARCHIVE_HIST/$ARCHIVE_FILES" .
-   if [ $? -ne 0 ] ; then
-     echo "Error on msrcp -overwrite sizemismatch mss:"$ARCHIVE_HIST"/"$ARCHIVE_FILES
-     exit 1
-   else
-#
-# Parse filename(s) and untar if necessary
-#
-     for FILE in `echo $ARCHIVE_FILES` ; do
-       FLEN=`echo $FILE | wc -c`
-       NDOT=0
-       CSTR=1
-       while [ $CSTR -le $FLEN ] ; do
-         CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
-         if [ "$CURC" = "." ] ; then
-           NDOT=`expr '(' $NDOT ')' '+' '1'`
-         fi
-         CSTR=`expr '(' $CSTR ')' '+' '1'`
-       done
-       NDOT=`expr '(' $NDOT ')' '+' '1'`
-       CURC=`echo $FILE | cut -d "." -f${NDOT}-${NDOT}`
-       if [ "$CURC" = "tar" ] ; then
-         tar xf $FILE
-         if [ $? -ne 0 ] ; then
-           echo "tar extraction failed on "$FILE
-           exit 1
-         else
-          rm -f  $FILE
-         fi
-       fi
-     done
-   fi
-#
 # If NERSC/ORNL hsi command exists, use it.
 #
-else
-  TEST4HSI=`which hsi 2<&1`
-  if [ $? -eq 0 ] ; then
-    if [ `echo $LST | cut -d"." -f2` = "tar" ] ; then
-      htar -x -f $ARCHIVE_HIST/$ARCHIVE_FILES
-      if [ $? -ne 0 ] ; then
-        hsi -q "get -U $ARCHIVE_HIST/$ARCHIVE_FILES"
-        if [ $? -eq 0 ] ; then
-          tar xf $ARCHIVE_FILES
-          if [ $? -ne 0 ] ; then
-            echo "htar and tar extraction failed on "$ARCHIVE_FILES
-            exit 1
-          else
-            rm -f  $ARCHIVE_FILES
-          fi
-        else
-          echo "Error on hsi get of "$ARCHIVE_HIST"/"$ARCHIVE_FILES
+TEST4HSI=`which hsi 2<&1`
+if [ $? -eq 0 ] ; then
+  if [ `echo $LST | cut -d"." -f2` = "tar" ] ; then
+    htar -x -f $ARCHIVE_HIST/$ARCHIVE_FILES
+    if [ $? -ne 0 ] ; then
+      hsi -q "get -U $ARCHIVE_HIST/$ARCHIVE_FILES"
+      if [ $? -eq 0 ] ; then
+        tar xf $ARCHIVE_FILES
+        if [ $? -ne 0 ] ; then
+          echo "htar and tar extraction failed on "$ARCHIVE_FILES
+	    ./procstat.sh error mss_read
           exit 1
+        else
+          rm -f  $ARCHIVE_FILES
         fi
-      fi
-    else
-      hsi -q "get $ARCHIVE_HIST/$ARCHIVE_FILES" 2>&1
-      if [ $? -ne 0 ] ; then
+      else
         echo "Error on hsi get of "$ARCHIVE_HIST"/"$ARCHIVE_FILES
+	  ./procstat.sh error mss_read
         exit 1
       fi
     fi
   else
-    echo "Neither msrcp nor hsi exist."
-    exit 1
+    hsi -q "get $ARCHIVE_HIST/$ARCHIVE_FILES" 2>&1
+    if [ $? -ne 0 ] ; then
+      echo "Error on hsi get of "$ARCHIVE_HIST"/"$ARCHIVE_FILES
+	./procstat.sh error mss_read
+      exit 1
+    fi
   fi
+else
+  echo "Cannot find hsi command."
+  ./procstat.sh error mss_read
+  exit 1
 fi
diff --git a/mss_write b/mss_write
--- a/mss_write
+++ b/mss_write
@@ -12,58 +12,36 @@ else
   echo "I need two arguments:"
   echo "1) file to write"
   echo "2) directory on archival system to write file to"
+  ./procstat.sh error mss_write
   exit 1
 fi
 #
 if [ ! -f $ARCHIVE_F ] ; then
   echo $MMSF" not present, cannot write to the archival system"
+  ./procstat.sh error mss_write
   exit 1
 fi
 #
-# If NCAR ARCHIVE_ msrcp command exists, use it.
-# Must check for msrcp first, to avoid using hsi at NCAR too early
-#
-TEST4MSRCP=`which msrcp 2<&1`
-if [ $? -eq 0 ] ; then
-  MSRCP=`which msrcp`
-#
-# Check for total length > 128 characters and attempt to modify
-#
-  ARCHIVE_R=${ARCHIVE_F}
-  TOTLEN=`echo ${ARCHIVE_D}"/"${ARCHIVE_F} | wc -c`
-  if [ $TOTLEN -gt 128 ] ; then
-    ARCHIVE_R=`echo $ARCHIVE_F | sed -e 's/track1\.//g'`
-    echo "Total ARCHIVE_ pathname too long (over 128 characters)"
-    echo "Renaming to "${ARCHIVE_R}
-  fi
-  $MSRCP -pe 3652 -class reliability=economy -srcdelete $ARCHIVE_F "mss:${ARCHIVE_D}/${ARCHIVE_R}"
-  if [ $? -eq 0 ] ; then
-    echo $ARCHIVE_R" written to "${ARCHIVE_D}/${ARCHIVE_R}" and erased."
-  else
-    echo "Problem with storing "${ARCHIVE_R}" to "${ARCHIVE_D}". Stopping."
-    exit 1
-  fi
-else
-#
 # If hsi command exists, use it.
 #
-  TEST4HSI=`which hsi 2<&1`
+TEST4HSI=`which hsi 2<&1`
+if [ $? -eq 0 ] ; then
+  HSI=`which hsi`
+  $HSI -q "mkdir -m 775 -p $ARCHIVE_D ; put -d -U ${ARCHIVE_D}/${ARCHIVE_F}" 2>&1
   if [ $? -eq 0 ] ; then
-    HSI=`which hsi`
-    $HSI -q "mkdir -m 775 -p $ARCHIVE_D ; put -d -U ${ARCHIVE_D}/${ARCHIVE_F}" 2>&1
-    if [ $? -eq 0 ] ; then
-      echo ${ARCHIVE_F}" written to "${ARCHIVE_D}" and erased."
-    else
-      $HSI -q "put -d ${ARCHIVE_F}" 2>&1
-      if [ $? -eq 0 ] ; then
-        echo ${ARCHIVE_F}" written to your HPSS HOME and erased."
-      else
-        echo "Problem with HPSS on "${ARCHIVE_F}". Stopping"
-        exit 1
-      fi
-    fi      
+    echo ${ARCHIVE_F}" written to "${ARCHIVE_D}" and erased."
   else
-    echo "Neither msrcp nor hsi exist. DIE."
-    exit 1
-  fi
+    $HSI -q "put -d ${ARCHIVE_F}" 2>&1
+    if [ $? -eq 0 ] ; then
+      echo ${ARCHIVE_F}" written to your HPSS HOME and erased."
+    else
+      echo "Problem with HPSS on "${ARCHIVE_F}". Stopping"
+	./procstat.sh error mss_write
+      exit 1
+    fi
+  fi      
+else
+  echo "Cannot find hsi command."
+  ./procstat.sh error mss_write
+  exit 1
 fi
