ORNL and NERSC changes

diff --git a/mss_list b/mss_list
--- a/mss_list
+++ b/mss_list
@@ -15,14 +15,27 @@ TEST4MSRCP=`which ncrcat 2<&1 >& /dev/null`
 if [ $? -eq 0 ] ; then
    rm -f ABCXYZ
    msls -1R "$MSSHIST" >& ABCXYZ
-   egrep "$HISTNAM" ABCXYZ >& $MSSL
-   rm -f ABCXYZ
+   if [ $? -eq 0 ] ; then
+     egrep "$HISTNAM" ABCXYZ >& $MSSL
+     rm -f ABCXYZ
+   else
+     echo "Error on mss_list from "$MSSHIST
+     exit 1
+   fi
 #
 # If NERSC/ORNL hsi command exists, use it.
 else
   TEST4HSI=`which hsi 2<&1 >& /dev/null`
   if [ $? -eq 0 ] ; then
-    hsi -q "ls -1 ${MSSHIST}" | egrep $HISTNAME >& $MSSL
+    rm -f ABCXYZ
+    hsi -q "ls -1 ${MSSHIST}" >& ABCXYZ
+    if [ $? -eq 0 ] ; then
+      egrep "$HISTNAME" ABCXYZ >& $MSSL
+      rm -f ABCXYZ
+    else
+      echo "Error on mss_list from "$MSSHIST
+      exit 1
+    fi
   else
     echo "Neither msrcp nor hsi exist."
     exit 1
