Tweaked mss_read

diff --git a/mss_read b/mss_read
--- a/mss_read
+++ b/mss_read
@@ -39,14 +39,7 @@ if [ $? -eq 0 ] ; then
 else
   TEST4HSI=`which hsi 2<&1 >& /dev/null`
   if [ $? -eq 0 ] ; then
-    echo "LST is "$LST
-    if [ `echo $LST | cut -d"." -f2` != ".tar" ] ; then
-      hsi -q "get $MSSHIST/$MSSFILES" >& /dev/null
-      if [ $? -ne 0 ] ; then
-        echo "Error on hsi get of "$MSSHIST"/"$MSSFILES
-        exit 1
-      fi
-    else
+    if [ `echo $LST | cut -d"." -f2` = "tar" ] ; then
       htar -x -f $MSSHIST/$MSSFILES
       if [ $? -ne 0 ] ; then
         hsi -q "get -U $MSSHIST/$MSSFILES" >& /dev/null
@@ -60,6 +53,12 @@ else
           echo "Error on hsi get of "$MSSHIST"/"$MSSFILES
           exit 1
         fi
+      fi
+    else
+      hsi -q "get $MSSHIST/$MSSFILES" >& /dev/null
+      if [ $? -ne 0 ] ; then
+        echo "Error on hsi get of "$MSSHIST"/"$MSSFILES
+        exit 1
       fi
     fi
   else
