CMIP5 script interface changes

diff --git a/mss_var_read b/mss_var_read
--- a/mss_var_read
+++ b/mss_var_read
@@ -2,43 +2,39 @@
 # Read file(s) from a archival system
 #
 if [ $# -ne 2 ] ; then
-  echo "Usage: mss_read ARCHIVE_LIST YEARNOW"
-  echo "Requires ARCHIVE_LIST and YEARNOW"
-  echo "CASE HIST ARCHIVE_HIST must be defined"
-  ./procstat.sh error mss_read
+  echo "Usage: mss_var_read ARCHIVE_PROC VARS"
+  echo "Requires ARCHIVE_PROC and VARS"
+#  ./procstat.sh error mss_var_read
   exit 1
 else
-  ARCHIVE_LIST=$1
-  YEARNOW=$2
+  ARCHIVE_PROC=$1
+  VARS=$2
 fi
 #
-if ! [ -f $ARCHIVE_LIST ] ; then
-  echo "mss_read: No "$ARCHIVE_LIST" file found. Exit."
-  ./procstat.sh error mss_read
+if ! [ $ARCHIVE_PROC ] ; then
+  echo "mss_var_read: "$ARCHIVE_PROC" undefined. Exit."
+  ./procstat.sh error mss_var_read
   exit 1
 fi
-if [ ! $CASE ] ; then
-  echo "mss_read: CASE undefined. Exit."
-fi
 if [ ! $HIST ] ; then
-  echo "mss_read: HIST undefined. Exit."
+  echo "mss_var_read: HIST undefined. Exit."
 fi
-if [ ! $ARCHIVE_HIST ] ; then
-  echo "mss_read: ARCHIVE_HIST undefined. Exit."
+if [ ! $VARS ] ; then
+  echo "mss_var_read: VARS undefined. Exit."
 fi
 #
 # Get files - check if hsi exists first
 #
 TEST4HSI=`which hsi 2<&1`
 if [ $? -eq 0 ] ; then
-  hsi -q "cget -u ${ARCHIVE_HIST}/${CASE}.${HIST}.{${VARS}}.*"
+  hsi -q "cd ${ARCHIVE_PROC} ; cget -u *.${HIST}.{${VARS}}.*.nc"
   if [ $? -ne 0 ] ; then
-    echo "Error on hsi get of "$ARCHIVE_HIST"/"$ARCHIVE_FILES
-    ./procstat.sh error mss_read
+    echo "Error on hsi get of "$ARCHIVE_PROC" files. Stopping."
+#    ./procstat.sh error mss_var_read
     exit 1
   fi
 else
   echo "Cannot find hsi command."
-  ./procstat.sh error mss_read
+#  ./procstat.sh error mss_var_read
   exit 1
 fi
