ORNL and NERSC changes

diff --git a/mss_read b/mss_read
--- a/mss_read
+++ b/mss_read
@@ -18,12 +18,20 @@ fi
 TEST4MSRCP=`which msrcp 2<&1 >& /dev/null`
 if [ $? -eq 0 ] ; then
    msrcp -overwrite sizemismatch mss:"$MSSD/$MSSF" .
+   if [ $? -ne 0 ] ; then
+     echo "Error on msrcp -overwrite sizemismatch mss:"$MSSD"/"$MSSF
+     exit 1
+   fi
 #
 # If NERSC/ORNL hsi command exists, use it.
 else
   TEST4HSI=`which hsi 2<&1 >& /dev/null`
   if [ $? -eq 0 ] ; then
-     hsi -q "get -U $MSSD/$MSSF"
+     hsi -q "get -U $MSSD/$MSSF" >& /dev/null
+     if [ $? -ne 0 ] ; then
+       echo "Error on hsi -q get -U "$MSSD"/"$MSSF
+       exit 1
+     fi
   else
     echo "Neither msrcp nor hsi exist."
     exit 1
