More fixes

diff --git a/Process_Data b/Process_Data
--- a/Process_Data
+++ b/Process_Data
@@ -7,15 +7,15 @@
 # --------------------------------------------------------------------------------
 # Case(s)
 #
-CASES="b30.097b"
+CASELIST="b30.030a"
 #
 # Type(s) - one of "atmm atmd lndm ocnm icem"
 #
-TYPES="lndm"
+TYPELIST="icem"
 #
 # Whether or not to do IPCC processing (zero means DO NOT, non-zero means DO)
 #
-DO_IPCC=0 ; export DO_IPCC
+DO_IPCC=1 ; export DO_IPCC
 #
 # Whether or not to do single-field processing (zero means DO NOT, non-zero means DO)
 # one for each type above
@@ -24,9 +24,9 @@ DO_PROC=1 ; export DO_PROC
 #
 CURDIR=$PWD
 #
-for CASE in $CASES ; do
+for CASE in $CASELIST ; do
   export CASE
-  for TYPE in $TYPES ; do
+  for TYPE in $TYPELIST ; do
     export TYPE
 # --------------------------------------------------------------------------------
 # Set up all necessary script variables
@@ -42,41 +42,60 @@ for CASE in $CASES ; do
     cd $PROCDIR
     YEARNOW=$YEARBEG
     while [ $YEARNOW -le $YEAREND ] ; do
-      YRCHECK=.done.$CASE.$HISTNAM.$YEARNOW
+      YRCHECK=.comp.$CASE.$HISTNAM.$YEARNOW
       if [ ! -f $YRCHECK ] ; then
         echo "Processing "$CASE"."$HISTNAM"."$YEARNOW" at "`date`
-        if [ $TYPE != "atmd" ] ; then
-          MSFILES=$CASE.$HISTNAM.$YEARNOW-{01,02,03,04,05,06,07,08,09,10,11,12}.nc
-        else
-          MSSLIST=MSS.$CASE.$TYPE
-          if [ ! -f $MSSLIST ] ; then
-            echo "Getting archival list of "$CASE" "$HISTNAM
-            ./mss_list $MSSLIST
-          fi
-          CHEK=`echo $CASE | cut -d"." -f3 | cut -c1-2`
-          if [ ! $CHEK ] ; then
-            DAT=`/bin/egrep "$YEARNOW" $MSSLIST | cut -d"." -f5 | cut -d"-" -f2-3`
-          else
-            DAT=`/bin/egrep "$YEARNOW" $MSSLIST | cut -d"." -f5 | cut -d"-" -f2-3`
-          fi
-          LST=`echo $DAT | sed -e "s/ /,/g"`
-          MSFILES=$CASE.$HISTNAM.${YEARNOW}-"{"${LST}"}"-00000.nc
-          echo $MSFILES
+        MSSLIST=MSS.$CASE.$TYPE
+        if [ ! -f $MSSLIST ] ; then
+          echo "Getting archival list of "$CASE" "$HISTNAM
+          ./mss_list $MSSLIST
         fi
+        CHEK=`echo $CASE | cut -d"." -f3 | cut -c1-2`
+        if [ ! $CHEK ] ; then
+          DAT=`/bin/egrep "$YEARNOW\-" $MSSLIST | cut -d"." -f5 | cut -d"-" -f2-3`
+        else
+          DAT=`/bin/egrep "$YEARNOW\-" $MSSLIST | cut -d"." -f5 | cut -d"-" -f2-3`
+        fi
+        LST=`echo $DAT | sed -e "s/ /,/g"`
+        if [ "$TYPE" = "atmd" ] ; then
+          MSFILES=$CASE.$HISTNAM.${YEARNOW}-"{"${LST}"}"-00000.nc
+        else
+          MSFILES=$CASE.$HISTNAM.${YEARNOW}-"{"${LST}"}".nc
+        fi
+#        echo $MSFILES
         ./mss_read $MSSHIST $MSFILES
         if [ $? -ne 0 ] ; then
           echo "Error from mss_read of "$MSFILES
           exit 1
         else
-          if [ $TYPE != "atmd" ] ; then
+          if [ "$TYPE" != "atmd" ] ; then
             for FILE in `ls $CASE.$HISTNAM.$YEARNOW-??.nc` ; do
               if [ $DO_IPCC -ne 0 ] ; then
-                ./create_ipcc_data $FILE
-                if [ $? -ne 0 ] ; then
-                  echo "Error from create_ipcc_data on file "$FILE
-                  exit 1
+                if [ "$TYPE" = "ocnm" ] || [ "$TYPE" = "icem" ] ; then
+                  ./regrid_data $FILE
+                  if [ $? -ne 0 ] ; then
+                    echo "Error from regrid_data on file "$FILE
+                    exit 1
+                  else
+                    for FINT in `ls $CASE.$HISTNAM.*.$YEARNOW-??.nc` ; do
+                      ./create_ipcc_data $FINT
+                      if [ $? -ne 0 ] ; then
+                        echo "Error from create_ipcc_data on file "$FINT
+                        exit 1
+                      else
+                        rm -f $FINT
+                      fi
+                    done
+                    touch .ipcc.$FILE
+                  fi
                 else
-                  touch .ipcc.$FILE
+                  ./create_ipcc_data $FILE
+                  if [ $? -ne 0 ] ; then
+                    echo "Error from create_ipcc_data on file "$FILE
+                    exit 1
+                  else
+                    touch .ipcc.$FILE
+                  fi
                 fi
               fi
               if [ $DO_PROC -ne 0 ] ; then
@@ -89,7 +108,7 @@ for CASE in $CASES ; do
                 fi
               fi
               if [ -f .proc.$FILE ] || [-f .ipcc.$FILE ] ; then
-                touch .done.$FILE
+                touch .comp.$FILE
                 rm -f .proc.$FILE .ipcc.$FILE
               fi
             done
@@ -118,15 +137,15 @@ for CASE in $CASES ; do
                 fi
               fi
               if [ -f .proc.$FILE ] || [-f .ipcc.$FILE ] ; then
-                touch .done.$FILE
+                touch .comp.$FILE
               fi
             done
           fi
         fi
-      fi
-      if [ `ls .done.$CASE.$HISTNAM.$YEARNOW-??.nc | wc -l` -eq 12 ] ; then
-        touch $YRCHECK
-        rm .done.$CASE.$HISTNAM.$YEARNOW-??.nc
+        if [ `ls .comp.$CASE.$HISTNAM.$YEARNOW-??.nc | wc -l` -eq 12 ] ; then
+          touch $YRCHECK
+          rm .????.$CASE.$HISTNAM.$YEARNOW-??.nc
+        fi
       fi
       YEARNOW=`expr $YEARNOW + 1`
     done
@@ -137,7 +156,7 @@ for CASE in $CASES ; do
 #
 # Store completed data on archival system
 #
-    ./store_to_archive
+#    ./store_to_archive
 #
   cd $CURDIR
   done # TYPE
diff --git a/cf_var_all_concat b/cf_var_all_concat
--- a/cf_var_all_concat
+++ b/cf_var_all_concat
@@ -1,58 +1,111 @@
-#!/bin/csh -f
+#!/bin/sh
 #
 # Concatenate decades of IPCC netCDF files into bigger chunks
 #
-if ("$#argv" != 0) then
+if [ "$#argv" != 0 ] ; then
    echo "Usage: cf_var_all_concat"
    exit 1
-endif
+fi
+# 
+# Check for ncrcat
 #
-set table  = `ls | egrep '\.nc$' | cut -d"_" -f2 | cut -d"." -f1 | sort | uniq`
-set expids = `ls | egrep '\.nc$' | cut -d"." -f2 | sort | uniq`
-set model  = `ls | egrep '\.nc$' | cut -d"." -f3 | sort | uniq`
-set comp   = `ls | egrep '\.nc$' | cut -d"." -f4 | sort | uniq`
+if [ ! $NCRCAT ] ; then
+   TEST4NCRCAT=`which ncrcat 2<&1 >& /dev/null`
+   if [ $? -eq 0 ] ; then
+     NCRCAT=`which ncrcat`
+   else
+     echo "NCRCAT not in PATH - UNDEFINED"
+     exit 1
+   fi
+fi
 #
-foreach m (${model})
-  foreach c (${comp})
-    foreach t (${table})
-      if (${t} == "A2") then
-        set vars = `ls *_${t}.*.${m}.${c}.????-??-??_cat_????-??-??.nc | cut -d"_" -f1 | uniq`
-      else
-        set vars = `ls *_${t}.*.${m}.${c}.????-??_cat_????-??.nc | cut -d"_" -f1 | uniq`
-      endif
-      foreach v (${vars})
-        foreach e (${expids})
-          if (${t} == "A2") then
-            set f1 = `ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??.nc | head -1`
-            set f2 = `ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??.nc | tail -1`
-            set t1 = `echo ${f1} | cut -d"." -f5 | cut -c1-10`
-            set t2 = `echo ${f2} | cut -d"." -f5 | cut -c16-25`    
-            set tf = ${v}_${t}.${e}.${m}.${c}.${t1}_allcat_${t2}.nc
-            $CCPS_NCRCAT -h -O ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??.nc ${tf}
-            if ($status == 0) then
-              rm -f ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??.nc
-              set df = ${v}_${t}.${e}.${m}.${c}.${t1}_cat_${t2}.nc
-              mv ${tf} ${df}
-              echo "Completed "${df}
-            endif
+ TABLE=`ls | egrep '\.nc$' | cut -d"_" -F2 | cut -d"." -f1 | sort | uniq`
+EXPIDS=`ls | egrep '\.nc$' | cut -d"." -F2 | sort | uniq`
+ MODEL=`ls | egrep '\.nc$' | cut -d"." -f3 | sort | uniq`
+  COMP=`ls | egrep '\.nc$' | cut -d"." -f4 | sort | uniq`
+#
+for m in $MODEL ; do
+  for c in $COMP ; do
+    for t in $TABLE ; do
+      VARS=`ls *_${t}.*.${m}.${c}.*cat*_c??????.nc | cut -d"_" -f1 | uniq`
+      for v in $VARS ; do
+        for e in $EXPIDS ; do
+        if [ $DECOUNT ] ; then
+          echo "Concatenating of "${v}"."${t}"."${e}" files and checking decade counts: "$DECOUNT
+          if [ "$t" == "A2" ] ; then
+            NUM=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc | wc -l`
+            if [ $NUM = $DECOUNT ] ; then
+              F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc | head -1`
+              F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc | tail -1`
+              T1=`echo $F1 | cut -d"." -f5 | cut -c1-10`
+              T2=`echo $F2 | cut -d"." -f5 | cut -c16-25`
+              TS=`date '+%y%m%d'`
+              TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
+              $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc $TF
+              if [ $? -eq 0 ] ; then
+                rm -f ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc
+                DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
+                mv $TF $DF
+                echo "Completed "$DF
+              fi
+            else
+              echo "Missing decade(s) from "${v}"."${t}"."${e}" files"
+              echo "Count is "$NUM" should be "$DECOUNT
+              exit 1
+            fi
           else
-            set f1 = `ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??.nc | head -1`
-            set f2 = `ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??.nc | tail -1`
-            set t1 = `echo ${f1} | cut -d"." -f5 | cut -c1-7`
-            set t2 = `echo ${f2} | cut -d"." -f5 | cut -c13-19`    
-            set tf = ${v}_${t}.${e}.${m}.${c}.${t1}_allcat_${t2}.nc
-            $CCPS_NCRCAT -h -O ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??.nc ${tf}
-            if ($status == 0) then
-              rm -f ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??.nc
-              set df = ${v}_${t}.${e}.${m}.${c}.${t1}_cat_${t2}.nc
-              mv ${tf} ${df}
+            NUM=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc | wc -l`
+            if [ $NUM = $DECOUNT ] ; then
+              F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc | head -1`
+              F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc | tail -1`
+              T1=`echo $F1 | cut -d"." -f5 | cut -c1-7`
+              T2=`echo $F2 | cut -d"." -f5 | cut -c13-19`    
+              TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
+              $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc $TF
+              if [ $? -eq 0 ] ; then
+                rm -f ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc
+                DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
+                mv $TF $DF
+                echo "Completed "${df}
+              fi
+            else
+              echo "Missing decade(s) from "${v}"."${t}"."${e}" files"
+              echo "Count is "$NUM" should be "$DECOUNT
+              exit 1
+            fi
+          fi
+        else
+          echo "Concatenating of "${v}"."${t}"."${e}" files WITHOUT checking counts."
+          if [ "$t" == "A2" ] ; then
+            F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc | head -1`
+            F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc | tail -1`
+            T1=`echo $F1 | cut -d"." -f5 | cut -c1-10`
+            T2=`echo $F2 | cut -d"." -f5 | cut -c16-25`
+            TS=`date '+%y%m%d'`
+            TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
+            $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc $TF
+            if [ $? -eq 0 ] ; then
+              rm -f ${v}_${t}.${e}.${m}.${c}.????-??-??_cat_????-??-??_c??????.nc
+              DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
+              mv $TF $DF
+              echo "Completed "$DF
+            fi
+          else
+            F1=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc | head -1`
+            F2=`ls ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc | tail -1`
+            T1=`echo $F1 | cut -d"." -f5 | cut -c1-7`
+            T2=`echo $F2 | cut -d"." -f5 | cut -c13-19`    
+            TF=${v}_${t}.${e}.${m}.${c}.${T1}_allcat_${T2}_c${TS}.nc
+            $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc $TF
+            if [ $? -eq 0 ] ; then
+              rm -f ${v}_${t}.${e}.${m}.${c}.????-??_cat_????-??_c??????.nc
+              DF=${v}_${t}.${e}.${m}.${c}.${T1}_cat_${T2}_c${TS}.nc
+              mv $TF $DF
               echo "Completed "${df}
-            endif
-          endif
-        end
-      end
-    end
-  end
-end
-#
-exit
+            fi
+          fi
+        done
+      done
+    done
+  done
+done
diff --git a/create_ipcc_data b/create_ipcc_data
--- a/create_ipcc_data
+++ b/create_ipcc_data
@@ -1,100 +1,61 @@
 #!/bin/sh
 #
 if [ $# = 1 ] ; then
-   FILE=$1
+  NCL_FILE=$1
 else
-   echo "Usage: create_ipcc_data file"
-   exit 1
+  echo "Usage: create_ipcc_data file"
+  exit 1
 fi
 #
-if [ ! -f $file] ; then
-   echo $file "not found. Exit."
-   exit 1
+if [ ! -f $NCL_FILE ] ; then
+  echo $NCL_FILE "not found. Exit."
+  exit 1
+fi
+# 
+# Check for ncks
+#
+if [ ! $NCL ] ; then
+   TEST4NCL=`which ncl 2<&1 >& /dev/null`
+   if [ $? -eq 0 ] ; then
+     NCL=`which ncl`
+   else
+     echo "NCL not in PATH - UNDEFINED"
+     exit 1
+   fi
 fi
 #
-# Get correct NCL binary
+export NCL_FILE
 #
-case "$MACHINE" in
-  mineral* )                               # mineral @ CGD/NCAR
-    CCPS_NCL=/contrib/bin/ncl
-    NCARG_ROOT=/contrib/ncarg  ; export NCARG_ROOT ;;
-  davinci* )                               # davinci @ NERSC
-    CCPS_NCL=/usr/common/usg/ncar/5.0.0/bin/ncl
-    NCARG_ROOT=/usr/common/usg/ncar/5.0.0 ; export NCARG_ROOT ;;
-  lens* )                                  # lens @ ORNL
-    CCPS_NCL=/ccs/home/wgstrand/bin/ncl
-    NCARG_ROOT=/sw/analysis-x64/ncl/5.0.0/sl5.0_binary
-  * )
-    echo "Unable to run NCL from create_ipcc_data because "$MACHINE" not found."
-    exit 1 ;;
-esac
-#
-# Assume filename is of form bxx.xxxx.(pop|csim|clm2|cam2).hh.dddd-dd.nc
-# bxx.xx              : case name and number
-# (pop|csim|clm2|cam2): component
-# hh                  : stream
-# dddd                : time period
-#
-ISES=`ls $FILE | cut -d"." -f3 | cut -c1-2 | uniq`
-if [ $ISES == "ES"] ; then
-  FCASE=3 ; FCOMP=4 ; FSTRM=5 ; FTVAL=6
+CHEK=`ls $NCL_FILE | cut -d"." -f3 | cut -c1-2 | uniq`
+if [ $CHEK == "ES" ] ; then
+  F_TVAL=6
 else
-  FCASE=2 ; FCOMP=3 ; FSTRM=4 ; FTVAL=5
+  F_TVAL=5
 fi
 #
-CASE=`echo $FILE | cut -d"." -f1-$FCASE`
-COMP=`echo $FILE | cut -d"." -f$FCOMP`
-STRM=`echo $FILE | cut -d"." -f$FSTRM`
-TVAL=`echo $FILE | cut -d"." -f$FTVAL`
+NCL_TVAL=`echo $NCL_FILE | cut -d"." -f${F_TVAL}`
+NCL_SCRIPT=CCSM_${TYPE}_2cf.ncl ; export NCL_SCRIPT
 #
-if [ ! -d ./IPCC] ; then
+if [ ! -d ./IPCC ] ; then
    mkdir ./IPCC
-if
+fi
 #
-if [ $COMP == "cam2" ] ; then
-  if [ $STRM == "h0" ] ; then
-    COMP=atmm
-    NCL_SCPT=CCSM_atmm_2cf.ncl
-  elif [ $STRM == "h1" ] ; then
-    COMP=atmd
-    NCL_SCPT=atmd_2cf.ncl
-  fi
-  $CCPS_NCL < $NCL_SCPT
-  if [ $? -ne 0 ] ; then
-     echo "NCL ERROR"
-     exit 1
-  fi
-elif [ $comp == "clm2" ] ; then
-    COMP=lndm
-    NCL_SCPT=CCSM_lndm_2cf.ncl
-    $CCPS_NCL < $NCL_SCPT
-    if [ $? -ne 0 ] ; then
-      echo "NCL ERROR"
-      exit 1
+if [ "$TYPE" = "icem" ] || [ "$TYPE" = "ocnm" ] ; then # We are processing regridded ocean/ice data
+  F_TVAL=`expr $F_TVAL + 1`
+  NCL_TVAL=`echo $NCL_FILE | cut -d"." -f${F_TVAL}`
+  if [ "$TYPE" = "ocnm" ] ; then
+    if [ "$NCL_TVAL" = "nc" ] ; then # We are processing an original ocean file for transports
+      F_TVAL=`expr $F_TVAL - 1`
+      NCL_TVAL=`echo $NCL_FILE | cut -d"." -f${F_TVAL}`
+      NCL_SCRIPT=CCSM_trans_2cf.ncl ; export NCL_SCRIPT
     fi
-elif [ $comp == "csim" ] ; then
-  ./regrid_data $file
-  FTVAL=`expr $FTVAL + 1`
-  COMP=icem
-  NCL_SCPT=CCSM_icem_2cf.ncl
-  for FILE in `ls $CASE.csim.h.*.*.nc` ; do
-    TVAL=`echo $file | cut -d"." -f$FTVAL`
-    $CCPS_NCL < $NCL_SCPT
-    if [ $? -ne 0 ] ; then
-       echo "NCL ERROR"
-       exit 1
-    fi
-  done
-elif [ $comp == "pop" ] ; then
-  FTVAL=`expr $FTVAL + 1`
-  TVAL=`echo $file | cut -d"." -f$FTVAL`
-  COMP=ocnm
-  NCL_SCPT=CCSM_ocnm_2cf.ncl
-  $CCPS_NCL < $NCL_SCPT
-  if [ $? -ne 0 ] ; then
-     echo "NCL ERROR"
-     exit 1
   fi
 fi
 #
-exit
+export NCL_TVAL
+NCL_VERSION=`$NCL -V` ; export NCL_VERSION
+$NCL < $NCL_SCRIPT 2<&1 >& /dev/null
+if [ $? -ne 0 ] ; then
+   echo "NCL ERROR on "$NCL_FILE
+   exit 1
+fi
diff --git a/process_setup b/process_setup
--- a/process_setup
+++ b/process_setup
@@ -20,11 +20,14 @@ fi
 if [ -f ./experiments.txt ] ; then
   LOCATION=`egrep "^$CASE " experiments.txt | cut -c20-  | cut -d" " -f1`
    DESCRIP=`egrep "^$CASE " experiments.txt | cut -c25-  | cut -d" " -f1`
+   REALIZN=`egrep "^$CASE " experiments.txt | cut -c40-  | cut -d" " -f1`
     PARENT=`egrep "^$CASE " experiments.txt | cut -c50-  | cut -d" " -f1`
     BRANCH=`egrep "^$CASE " experiments.txt | cut -c65-  | cut -d" " -f1`
    YEARBEG=`egrep "^$CASE " experiments.txt | cut -c80-  | cut -d" " -f1`
    YEAREND=`egrep "^$CASE " experiments.txt | cut -c85-  | cut -d" " -f1`
-  HISTBASE=`egrep "^$CASE " experiments.txt | cut -c100- | cut -d" " -f1`
+       RES=`egrep "^$CASE " experiments.txt | cut -c90-  | cut -d" " -f1`
+  HARDWARE=`egrep "^$CASE " experiments.txt | cut -c100- | cut -d" " -f1`
+  HISTBASE=`egrep "^$CASE " experiments.txt | cut -c110- | cut -d" " -f1`
 else
   echo "Cannot find experiments.txt. HELP"
   exit 1
@@ -45,13 +48,13 @@ MNCOUNT=`expr '(' '(' $YEAREND '-' $YEARBEG ')' '+' '1' ')' '*' '12'`
 case "$LOCATION" in
   NC )                                        # NCAR experiments
     MSSBASE=/CCSM/csm/$CASE
-    MACHINE="mineral"  ;;
+    PROCHOST="mineral"  ;;
   NE )                                        # NERSC experiments
     MSSBASE=/nersc/mp9/strandwg/CCSM/csm/$CASE
-    MACHINE="davinci"  ;;
+    PROCHOST="davinci"  ;;
   OR )                                        # ORNL experiments
     MSSBASE=/f2/wgstrand/CCSM/csm/$CASE
-    MACHINE="lens0"    ;;
+    PROCHOST="lens0"    ;;
   * )
     echo "Unable to set variables because "$LOCATION" not found in experiments.txt"
     exit 1 ;;
@@ -92,30 +95,37 @@ esac
 #
 # resolve machine/site dependencies
 #
-case "$MACHINE" in 
+case "$PROCHOST" in 
   mineral* )                                # mineral @ CGD/NCAR
     BASEDIR=/home/strandwg/data/CCP_Processing_Suite
-    CCPS_NCKS=/usr/local/bin/ncks ; export CCPS_NCKS
-    CCPS_NCRCAT=/usr/local/bin/ncrcat ; export CCPS_NCRCAT
+    NCKS=/usr/local/bin/ncks ; export NCKS
+    NCRCAT=/usr/local/bin/ncrcat ; export NCRCAT
+    NCL=/contrib/bin/ncl ; export NCL
     case "$TYPE" in
       atmm ) PROCDIR=/datalocal/ccpg/$USER/$CASE/atm/mon ;;
       atmd ) PROCDIR=/datalocal/ccpg/$USER/$CASE/atm/day ;;
       lndm ) PROCDIR=/datalocal/ccpg/$USER/$CASE/lnd/mon ;;
       ocnm ) 
         PROCDIR=/datalocal/ccpg/$USER/$CASE/ocn/mon
-        REGRDIR=/project/ccr/strandwg/IPCC_Processing/ocn/CCSM
-        OREGRID=$BASEDIR/regridding/ccsm_ocn_rgd.mineral
-        if [ ! -f $OREGRID ] ; then
-          echo "Need to build OCN regridding code. Do that and re-run."
-          exit 1
+        if [ $DO_IPCC -ne 0 ] ; then
+          REGRDIR=/project/ccr/strandwg/IPCC_Processing/ocn/CCSM ; export REGRDIR
+          NAMLDIR=$BASEDIR/regridding                            ; export NAMLDIR
+          OREGRID=$BASEDIR/regridding/ccsm_ocn_rgd.mineral       ; export OREGRID
+          if [ ! -f $OREGRID ] ; then
+            echo "Need to build OCN regridding code. Do that and re-run."
+            exit 1
+          fi
         fi ;;
       icem ) 
-        PROCDIR=/datalocal/ccpg/$USER/$CASE/ocn/mon
-        REGRDIR=/project/ccr/strandwg/IPCC_Processing/ice/CCSM
-        IREGRID=$BASEDIR/regridding/ccsm_ice_rgd.mineral
-        if [ ! -f $IREGRID ] ; then
-          echo "Need to build ICE regridding code. Do that and re-run."
-          exit 1
+        PROCDIR=/datalocal/ccpg/$USER/$CASE/ice/mon
+        if [ $DO_IPCC -ne 0 ] ; then
+          REGRDIR=/project/ccr/strandwg/IPCC_Processing/ice/CCSM ; export REGRDIR
+          NAMLDIR=$BASEDIR/regridding                            ; export NAMLDIR
+          IREGRID=$BASEDIR/regridding/ccsm_ice_rgd.mineral       ; export IREGRID
+          if [ ! -f $IREGRID ] ; then
+            echo "Need to build ICE regridding code. Do that and re-run."
+            exit 1
+          fi
         fi ;;
       * ) 
         echo "Unable to continue because "$TYPE" not known."
@@ -124,8 +134,8 @@ case "$MACHINE" in
 
   davinci* )                                # davinci @ NERSC
     BASEDIR=/usr/common/homes/s/strandwg/CCP_Processing_Suite
-    CCPS_NCKS=/usr/common/homes/s/strandwg/bin/ncks ; export CCPS_NCKS
-    CCPS_NCRCAT=/usr/common/homes/s/strandwg/bin/ncrcat ; export CCPS_NCRCAT
+    NCKS=/usr/common/homes/s/strandwg/bin/ncks ; export NCKS
+    NCRCAT=/usr/common/homes/s/strandwg/bin/ncrcat ; export NCRCAT
     case "$TYPE" in
       atmm ) PROCDIR=/scratch/scratchdirs/$USER/$CASE/atm/mon ;;
       atmd ) PROCDIR=/scratch/scratchdirs/$USER/$CASE/atm/day ;;
@@ -145,9 +155,7 @@ case "$MACHINE" in
         if [ ! -f $IREGRID ] ; then
           echo "Need to build ICE regridding code. Do that and re-run."
           exit 1
-        else
-          setenv CCSM_ICE_RGD $IREGRID
-         fi ;;
+        fi ;;
       * ) 
         echo "Unable to continue because "$TYPE" not known."
         exit 1 ;;
@@ -155,8 +163,8 @@ case "$MACHINE" in
 
   lens* )                                # lens @ ORNL
     BASEDIR=/ccs/home/wgstrand/CCP_Processing_Suite
-    CCPS_NCKS=/ccs/home/wgstrand/bin/ncks ; export CCPS_NCKS
-    CCPS_NCRCAT=/ccs/home/wgstrand/bin/ncrcat ; export CCPS_NCRCAT
+    NCKS=/ccs/home/wgstrand/bin/ncks ; export NCKS
+    NCRCAT=/ccs/home/wgstrand/bin/ncrcat ; export NCRCAT
     case "$TYPE" in
       atmm ) PROCDIR=/tmp/work/$USER/$CASE/atm/mon ;;
       atmd ) PROCDIR=/tmp/work/$USER/$CASE/atm/day ;;
@@ -182,7 +190,7 @@ case "$MACHINE" in
         exit 1 ;;
     esac ;;
   * ) 
-    echo "Unable to continue because "$MACHINE" not known."
+    echo "Unable to continue because "$PROCHOST" not known."
     exit 1 ;;
 esac
 CACHEDIR=${PROCDIR}/to_archive
@@ -193,10 +201,39 @@ echo " process_setup as of : "`date`
 echo ""
 echo "           Case name : "$CASE     ; export CASE
 echo "     Processing type : "$TYPE     ; export TYPE
+if [ $DO_PROC -ne 0 ] ; then
+  echo "   by var processing : YES"
+else
+  echo "   by var processing : NO"
+fi
+if [ $DO_IPCC -ne 0 ] ; then
+  echo "     IPCC processing : YES"
+  if [ "$TYPE" = "ocnm" ] ; then
+    echo "regridding directory : "$REGRDIR
+    echo "   regridding binary : "$OREGRID
+  elif [ "$TYPE" = "icem" ] ; then
+    echo "regridding directory : "$REGRDIR
+    echo "   regridding binary : "$IREGRID
+  fi
+else
+  echo "     IPCC processing : NO"
+fi
+if [ "$LOCATION" = "NC" ] ; then
+  HARDWARE=${HARDWARE}".ucar.edu"
+fi
+if [ "$LOCATION" = "NE" ] ; then
+  HARDWARE=${HARDWARE}".nersc.gov"
+fi
+if [ "$LOCATION" = "OR" ] ; then
+  HARDWARE=${HARDWARE}".ccs.ornl.gov"
+fi
 echo "            Location : "$LOCATION ; export LOCATION
 echo "         Description : "$DESCRIP  ; export DESCRIP
+echo "         Realization : "$REALIZN  ; export REALIZN
 echo "         Parent case : "$PARENT   ; export PARENT
 echo "         Branch date : "$BRANCH   ; export BRANCH
+echo "          Resolution : "$RES      ; export RES
+echo "            Hardware : "$HARDWARE ; export HARDWARE
 echo "          Begin year : "$YEARBEG  ; export YEARBEG
 echo "            End year : "$YEAREND  ; export YEAREND
 echo "        Months count : "$MNCOUNT  ; export MNCOUNT
@@ -208,7 +245,7 @@ echo "   Archival base dir : "$MSSBASE  ; export MSSBASE
 echo "   IPCC format files : "$MSSIPCC  ; export MSSIPCC
 echo "     Processed files : "$MSSPROC  ; export MSSPROC
 echo ""
-echo "     Processing host : "$MACHINE  ; export MACHINE
+echo "     Processing host : "$PROCHOST ; export PROCHOST
 echo "      Processing dir : "$PROCDIR  ; export PROCDIR
 echo "   Archive cache dir : "$CACHEDIR ; export CACHEDIR
 echo " Processing code dir : "$BASEDIR  ; export BASEDIR
@@ -225,10 +262,18 @@ if [ $DO_IPCC -ne 0 ] ; then
   if [ ! -d $PROCDIR/IPCC ] ; then
      mkdir -p $PROCDIR/IPCC
   fi
-  if [ $TYPE = "atmd" ] ; then
+  if [ "$TYPE" = "atmd" ] ; then
     ln -s -f $BASEDIR/time_split    .
     ln -s -f $BASEDIR/days_to_month .
   fi
+  if [ "$TYPE" = "ocnm" ] || [ "$TYPE" = "icem" ] ; then
+    ln -s -f $BASEDIR/regrid_data .
+    mkdir -p $PROCDIR/maps
+    cd $PROCDIR/maps
+    ln -s -f $REGRDIR/*T*.nc .
+    ln -s -f $REGRDIR/*U*.nc .
+  fi
+  cd $PROCDIR
   ln -s -f $BASEDIR/create_ipcc_data    .
   ln -s -f $BASEDIR/CCSM_${TYPE}_2cf.ncl   .
   ln -s -f $BASEDIR/attributes_ccsm.ncl .
@@ -239,7 +284,7 @@ if [ $DO_IPCC -ne 0 ] ; then
 fi
 #
 if [ $DO_PROC -ne 0 ] ; then
-  if [ $TYPE = "atmd" ] ; then
+  if [ "$TYPE" = "atmd" ] ; then
     ln -s -f $BASEDIR/time_split    .
     ln -s -f $BASEDIR/days_to_month .
   fi
diff --git a/var_split b/var_split
--- a/var_split
+++ b/var_split
@@ -1,4 +1,4 @@
-#!/bin/csh -f
+#!/bin/sh
 #
 # See http://www.cgd.ucar.edu/~njn01/ccsm/draft.html
 #
@@ -7,161 +7,158 @@
 # Output filenames of forms:
 # b30.030e.pop.h.TEMP.1870-01.nc (monthly average of TEMP, only)
 #
-if ("$#argv" == 0) then
+if [ $# -eq 0 ] ; then
    echo "Usage: ccsm_var_split file [erase]"
    echo "2 args means erase file after fields extracted."
    exit 1
-else if ("$#argv" == 1) then
-   set file = $argv[1]
-else if ("$#argv" == 2) then
-   set file = $argv[1]
+elif [ $# -eq 1 ] ; then
+   FILE=$1
+elif [ $# -eq 2 ] ; then
+   FILE=$1
 else
    echo "Usage: ccsm_var_split file [erase]"
    echo "2 args means erase file after fields extracted."
    exit 1
-endif
+fi
 #
-if !(-f ${file}) then
-   echo $file "not found. Exit."
+if [ ! -f $FILE ] ; then
+   echo $FILE "not found. Exit."
    exit 1
-endif
+fi
+# 
+# Check for ncks
 #
-# Get correct NCO binaries
+if [ ! $NCKS ] ; then
+   TEST4NCKS=`which ncks 2<&1 >& /dev/null`
+   if [ $? -eq 0 ] ; then
+     NCKS=`which ncks`
+   else
+     echo "NCKS not in PATH - UNDEFINED"
+     exit 1
+   fi
+fi
 #
-set machine = `hostname`
-switch($machine)
-  case "mineral*":                                # mineral @ CGD/NCAR
-    set ccps_ncks   = /usr/local/bin/ncks
-    set ccps_ncrcat = /usr/local/bin/ncrcat
-  breaksw
-  case "davinci*":                                # davinci @ NERSC
-    set ccps_ncks   = /usr/common/homes/s/strandwg/bin/ncks
-    set ccps_ncrcat = /usr/common/homes/s/strandwg/bin/ncrcat
-  breaksw
-  case "lens*":                                # lens @ ORNL
-    set ccps_ncks   = /ccs/home/wgstrand/bin/ncks
-    set ccps_ncrcat = /ccs/home/wgstrand/bin/ncrcat
-  breaksw
-endsw
-#
-setenv CCPS_NCKS   ${ccps_ncks}
-setenv CCPS_NCRCAT ${ccps_ncrcat}
-#
-set chek   = `echo $file | cut -d"." -f3 | cut -c1-2`
-if (${chek} == "ES") then
-  set outfp0 = `echo $file | cut -d"." -f1-5`
-  set outfp1 = `echo $file | cut -d"." -f6-`
+CHEK=`echo $FILE | cut -d"." -f3 | cut -c1-2`
+if [ "$CHEK" = "ES" ] ; then
+  OUTPFX=`echo $FILE | cut -d"." -f1-5`
+  OUTSFX=`echo $FILE | cut -d"." -f6-`
 else
-  set outfp0 = `echo $file | cut -d"." -f1-4`
-  set outfp1 = `echo $file | cut -d"." -f5-`
-endif
+  OUTPFX=`echo $FILE | cut -d"." -f1-4`
+  OUTSFX=`echo $FILE | cut -d"." -f5-`
+fi
 #
-set d0vars = `$CCPS_NCKS -m ${file} | egrep "# dim\. = 0" | cut -d":" -f1`
-set d1vars = `$CCPS_NCKS -m ${file} | egrep "# dim\. = 1" | cut -d":" -f1`
-set d2vars = `$CCPS_NCKS -m ${file} | egrep "# dim\. = 2" | cut -d":" -f1`
-set d3vars = `$CCPS_NCKS -m ${file} | egrep "# dim\. = 3" | cut -d":" -f1`
-set d4vars = `$CCPS_NCKS -m ${file} | egrep "# dim\. = 4" | cut -d":" -f1`
-set d5vars = `$CCPS_NCKS -m ${file} | egrep "# dim\. = 5" | cut -d":" -f1`
+D0VARS=`$NCKS -m $FILE | egrep "# dim\. = 0" | cut -d":" -f1`
+D1VARS=`$NCKS -m $FILE | egrep "# dim\. = 1" | cut -d":" -f1`
+D2VARS=`$NCKS -m $FILE | egrep "# dim\. = 2" | cut -d":" -f1`
+D3VARS=`$NCKS -m $FILE | egrep "# dim\. = 3" | cut -d":" -f1`
+D4VARS=`$NCKS -m $FILE | egrep "# dim\. = 4" | cut -d":" -f1`
+D5VARS=`$NCKS -m $FILE | egrep "# dim\. = 5" | cut -d":" -f1`
 #
 # Get auxiliary header fields
 #
-if (`echo ${d2vars} | wc -c` != 0) then
-  if (`echo ${d1vars} | wc -c` != 0) then
-    if (`echo ${d0vars} | wc -c` != 0) then
-      set d0head = `echo $d0vars | sed -e 's/ /,/g'`
-      set d1head = `echo $d1vars | sed -e 's/ /,/g'`
-      set d2head = `echo $d2vars | sed -e 's/ /,/g'`
-      set header = `echo $d0head","$d1head","$d2head | sed -e 's/^,//g'`
+if [ `echo $D2VARS | wc -w` -ne 0 ] ; then
+  if [ `echo $D1VARS | wc -w` -ne 0 ] ; then
+    if [ `echo $D0VARS | wc -w` -ne 0 ] ; then
+      D0HEAD=`echo $D0VARS | sed -e 's/ /,/g'`
+      D1HEAD=`echo $D1VARS | sed -e 's/ /,/g'`
+      D2HEAD=`echo $D2VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D0HEAD","$D1HEAD","$D2HEAD | sed -e 's/^,//g'`
     else
-      set d1head = `echo $d1vars | sed -e 's/ /,/g'`
-      set d2head = `echo $d2vars | sed -e 's/ /,/g'`
-      set header = `echo $d1head","$d2head | sed -e 's/^,//g'`
-    endif
+      D1HEAD=`echo $D1VARS | sed -e 's/ /,/g'`
+      D2HEAD=`echo $D2VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D1HEAD","$D2HEAD | sed -e 's/^,//g'`
+    fi
   else
-    if (`echo ${d0vars} | wc -c` != 0) then
-      set d0head = `echo $d0vars | sed -e 's/ /,/g'`
-      set d2head = `echo $d2vars | sed -e 's/ /,/g'`
-      set header = `echo $d0head","$d2head | sed -e 's/^,//g'`
+    if [ `echo $D0VARS | wc -w` -ne 0 ] ; then
+      D0HEAD=`echo $D0VARS | sed -e 's/ /,/g'`
+      D2HEAD=`echo $D2VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D0HEAD","$D2HEAD | sed -e 's/^,//g'`
     else
-      set d2head = `echo $d2vars | sed -e 's/ /,/g'`
-      set header = `echo $d2head | sed -e 's/^,//g'`
-    endif
-  endif
+      D2HEAD=`echo $D2VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D2HEAD | sed -e 's/^,//g'`
+    fi
+  fi
 else
-  if (`echo ${d1vars} | wc -c` != 0) then
-    if (`echo ${d0vars} | wc -c` != 0) then
-      set d0head = `echo $d0vars | sed -e 's/ /,/g'`
-      set d1head = `echo $d1vars | sed -e 's/ /,/g'`
-      set header = `echo $d0head","$d1head | sed -e 's/^,//g'`
+  if [ `echo $D1VARS | wc -w` -ne 0 ] ; then
+    if [ `echo $D0VARS | wc -w` -ne 0 ] ; then
+      D0HEAD=`echo $D0VARS | sed -e 's/ /,/g'`
+      D1HEAD=`echo $D1VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D0HEAD","$D1HEAD | sed -e 's/^,//g'`
     else
-      set d1head = `echo $d1vars | sed -e 's/ /,/g'`
-      set header = `echo $d1head | sed -e 's/^,//g'`
-    endif
+      D1HEAD=`echo $D1VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D1HEAD | sed -e 's/^,//g'`
+    fi
   else
-    if (`echo ${d0vars} | wc -c` != 0) then
-      set d0head = `echo $d0vars | sed -e 's/ /,/g'`
-      set header = `echo $d0head | sed -e 's/^,//g'`
+    if [ `echo $D0VARS | wc -w` -ne 0 ] ; then
+      D0HEAD=`echo $D0VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D0HEAD | sed -e 's/^,//g'`
     else
-      set d2head = `echo $d2vars | sed -e 's/ /,/g'`
-      set header = `echo $d2head | sed -e 's/^,//g'`
-    endif
-  endif
-endif
+      D2HEAD=`echo $D2VARS | sed -e 's/ /,/g'`
+      HEADER=`echo $D2HEAD | sed -e 's/^,//g'`
+    fi
+  fi
+fi
 #
 # Get variable fields
 #
-if (`echo ${d3vars} | wc -c` != 0) set fields3d = `echo $d3vars`
-if (`echo ${d4vars} | wc -c` != 0) set fields4d = `echo $d4vars`
-if (`echo ${d5vars} | wc -c` != 0) set fields5d = `echo $d5vars`
+if [ `echo $D3VARS | wc -w` -ne 0 ] ; then
+  FIELDS3D=`echo $D3VARS`
+fi
+if [ `echo $D4VARS | wc -w` -ne 0 ] ; then
+  FIELDS4D=`echo $D4VARS`
+fi
+if [ `echo $D5VARS | wc -w` -ne 0 ] ; then
+  FIELDS5D=`echo $D5VARS`
+fi
 #
 # 3D vars
 #
-if (`echo ${fields3d} | wc -c` != 0) then
-  foreach f ( `echo $fields3d` )
-    if !(-d ${f}_3d.d) then
+if [ `echo $FIELDS3D | wc -w` -ne 0 ] ; then
+  for f in $FIELDS3D ; do
+    if [ ! -d ${f}_3d.d ] ; then
       mkdir ${f}_3d.d
-    endif
-    set out = ${f}_3d.d/${outfp0}.${f}.${outfp1}
-    $CCPS_NCKS -h -O -v ${header},${f} ${file} ${out}
-    if ($status != 0) then
-      echo "$CCPS_NCKS -h -O -v ${header},${f} ${file} ${out} failed"
+    fi
+    OUT=${f}_3d.d/${OUTPFX}.${f}.${OUTSFX}
+    $NCKS -O -v ${HEADER},${f} $FILE $OUT
+    if [ $? -ne 0 ] ; then
+      echo "NCKS -O -v ${HEADER},${f} $FILE $OUT failed"
       exit 1
-    endif
-  end
-endif
+    fi
+  done
+fi
 #
 # 4D vars
 #
-if (`echo ${fields4d} | wc -c` != 0) then
-  foreach f ( `echo $fields4d` )
-    if !(-d ${f}_4d.d) then
+if [ `echo $FIELDS4D | wc -w` -ne 0 ] ; then
+  for f in $FIELDS4D ; do
+    if [ ! -d ${f}_4d.d ] ; then
       mkdir ${f}_4d.d
-    endif
-    set out = ${f}_4d.d/${outfp0}.${f}.${outfp1}
-    $CCPS_NCKS -h -O -v ${header},${f} ${file} ${out}
-    if ($status != 0) then
-      echo "$CCPS_NCKS -h -O -v ${header},${f} ${file} ${out} failed"
+    fi
+    OUT=${f}_4d.d/${OUTPFX}.${f}.${OUTSFX}
+    $NCKS -O -v ${HEADER},${f} $FILE $OUT
+    if [ $? -ne 0 ] ; then
+      echo "NCKS -O -v ${HEADER},${f} $FILE $OUT failed"
       exit 1
-    endif
-  end
-endif
+    fi
+  done
+fi
 #
 # 5D vars
 #
-if (`echo ${fields5d} | wc -c` != 0) then
-  foreach f ( `echo $fields5d` )
-    if !(-d ${f}_5d.d) then
+if [ `echo $FIELDS5D | wc -w` -ne 0 ] ; then
+  for f in $FIELDS5D ; do
+    if [ ! -d ${f}_5d.d ] ; then
       mkdir ${f}_5d.d
-    endif
-    set out = ${f}_5d.d/${outfp0}.${f}.${outfp1}
-    $CCPS_NCKS -h -O -v ${header},${f} ${file} ${out}
-    if ($status != 0) then
-      echo "$CCPS_NCKS -h -O -v ${header},${f} ${file} ${out} failed"
+    fi
+    OUT=${f}_5d.d/${OUTPFX}.${f}.${OUTSFX}
+    $NCKS -O -v ${HEADER},${f} $FILE $OUT
+    if [ $? -ne 0 ] ; then
+      echo "NCKS -O -v ${HEADER},${f} $FILE $OUT failed"
       exit 1
-    endif
-  end
-endif
+    fi
+  done
+fi
 #
-if ("$#argv" == 2) rm -f ${file}
-#
-exit
+if [ $# -gt 1 ] ; then
+  rm -f $FILE
+fi
