Changes for mirage3 and mirage4 batch submittals

diff --git a/Process_DP b/Process_DP
--- a/Process_DP
+++ b/Process_DP
@@ -1,11 +1,11 @@
 #!/bin/sh
 #
 if [ $# -ne 3 ] ; then
-   echo "Usage: ./Process_DP CASE HIST TPER"
+   echo "Usage: ./Process_Setup CASE HIST TPER"
    echo "All three arguments REQUIRED:"
    echo "1: CASE name"
    echo "2: HIST name - usually one of [cam2.h0 cam2.h1 cam2.h2 clm.h0 pop.h csim.h cice.h etc]"
-   echo "3: TPER time period of above HIST type - must be one of [mon day hr6 hr3]"
+   echo "3: TPER time period of above HIST type - must be one of [ann mon day hr6 hr3 m30]"
    exit 1
 elif [ $# -eq 3 ] ; then
    CASE=$1 ; export CASE
@@ -15,16 +15,14 @@ fi
 #
 # Set up a bunch of stuff
 #
-if [ $TPER != "mon" ] ; then
-  if [ $TPER != "day" ] ; then
-    if [ $TPER != "hr6" ] ; then
-      if [ $TPER != "hr3" ] ; then
-        echo "TPER must be one of [mon day hr6 hr3]"
-        exit 1
-      fi
-    fi
-  fi
-fi
+case "$TPER" in
+  ann | mon | day | hr6 | hr3 | m30 )
+    echo ${TPER}" is known time period. Proceeding." ;;
+  * ) 
+    echo "Unable to continue because "$TPER" is unknown. Stopping."
+    ./procstat.sh error Process_Setup
+    exit 1 ;;
+esac
 #
 EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
 if ! [ -f $EXPFILE ] ; then
@@ -34,29 +32,29 @@ fi
 #
 PROCHOST=`hostname`;export PROCHOST
 #
-# Start to build processing script
+# Build processing script
 #
-CCPS_SCRIPT=${CASE}_${HIST}_process.sh
+CCPS_SCRIPT=${CASE}_${HIST}_${TPER}_process.sh
 rm -f $CCPS_SCRIPT
 #
 case "$PROCHOST" in 
   silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | modeling1* | euclid* )  # NCAR and NERSC machines
     echo "#!/bin/sh" > $CCPS_SCRIPT
     cat ./process_dp_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                              | sed -e "s/xxxHISTxxx/$HIST/g" \
-                              | sed -e "s/xxxTPERxxx/$TPER/g" \
+                           | sed -e "s/xxxHISTxxx/$HIST/g" \
+                           | sed -e "s/xxxTPERxxx/$TPER/g" \
                            >> $CCPS_SCRIPT ;;
-  mirage3 | mirage4 )  # NCAR and NERSC machines
-    cat ./LSF_batch > $CCPS_SCRIPT
+  mirage3 | mirage4 )
+    cat ./LSF_batch | sed -e "s/NAME/$CCPS_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CCPS_SCRIPT
     cat ./process_dp_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                              | sed -e "s/xxxHISTxxx/$HIST/g" \
-                              | sed -e "s/xxxTPERxxx/$TPER/g" \
+                           | sed -e "s/xxxHISTxxx/$HIST/g" \
+                           | sed -e "s/xxxTPERxxx/$TPER/g" \
                            >> $CCPS_SCRIPT ;;
   lens* )                                  # lens @ ORNL
     cat ./ORNL_batch > $CCPS_SCRIPT
     cat ./process_dp_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                              | sed -e "s/xxxHISTxxx/$HIST/g" \
-                              | sed -e "s/xxxTPERxxx/$TPER/g" \
+                           | sed -e "s/xxxHISTxxx/$HIST/g" \
+                           | sed -e "s/xxxTPERxxx/$TPER/g" \
                            >> $CCPS_SCRIPT ;;
   * )
     echo "Unable to build script because "$PROCHOST" unknown."
@@ -78,7 +76,7 @@ if [ "$DORUN" = "Y" ] ; then
     lens* )
       ( /usr/bin/qsub ./${CCPS_SCRIPT} ) ;;
     mirage3 | mirage4 )
-      ( SOME_LSF_COMMAND ./${CCPS_SCRIPT} ) ;;
+      ( /fs/local/apps/lsf/8.0/linux2.6-glibc2.3-x86_64/bin/bsub < ./${CCPS_SCRIPT} ) ;;
     * )
       ( ./${CCPS_SCRIPT} > log.${CCPS_SCRIPT} 2>&1 & ) ;;
   esac
