Shift from var_extract to slice2series

diff --git a/process_pac_template b/process_pac_template
--- a/process_pac_template
+++ b/process_pac_template
@@ -247,17 +247,17 @@ echo -n "TS run_slice2series end   : " ; date
 #
 # Store completed data on archival system
 #
-echo -n "TS archive start: " ; date
-./store_to_archive_var
-if [ $? -ne 0 ] ; then
-  echo "store_to_archive failed"
-  ./update_status error "$CASE $HIST $TPER"
-  exit 1
-else
-  echo -n "TS archive end: " ; date
-fi
-#
-./update_status complete
-echo -n "TS COMPLETE: " ; date
+#echo -n "TS archive start: " ; date
+#./store_to_archive_var
+#if [ $? -ne 0 ] ; then
+#  echo "store_to_archive failed"
+#  ./update_status error "$CASE $HIST $TPER"
+#  exit 1
+#else
+#  echo -n "TS archive end: " ; date
+#fi
+##
+#./update_status complete
+#echo -n "TS COMPLETE: " ; date
 #
 exit
