Many bug fixes, conversion to Bourne shell from C-shell

diff --git a/Process_Data b/Process_Data
--- a/Process_Data
+++ b/Process_Data
@@ -1,103 +1,94 @@
-#!/bin/csh -f
+#!/bin/sh
 #
-# Process CCSM CAM monthly-mean netCDF files
-# Optionally, create IPCC format files
+# Process CCSM history netCDF files into single-field format and/or IPCC format
 #
 # --------------------------------------------------------------------------------
 # User-settable parameters
 # --------------------------------------------------------------------------------
 # Case(s)
 #
-set cases   = ( b30.097a )
+CASES="b30.097b"
 #
-# Type(s) (atmm atmd lndm ocnm icem )
+# Type(s) - one of "atmm atmd lndm ocnm icem"
 #
-set types   = ( atmm )
+TYPES="atmm"
 #
 # Whether or not to do IPCC processing (zero means DO NOT, non-zero means DO)
 #
-set do_ipcc = 0
+DO_IPCC=0 ; export DO_IPCC
 #
 # Whether or not to do single-field processing (zero means DO NOT, non-zero means DO)
 # one for each type above
 #
-set do_proc = 1
+DO_PROC=1 ; export DO_PROC
 #
-foreach c ( ${cases} )
-  foreach t ( ${types} )
+CURDIR=$PWD
+#
+for CASE in $CASES ; do
+  for TYPE in $TYPES ; do
 # --------------------------------------------------------------------------------
 # Set up all necessary script variables
 # --------------------------------------------------------------------------------
 #
-    source ./process_setup $c $t $do_proc $do_ipcc
-    if ($status != 0) then
-      echo "ERROR in setting up "${c}" "${t}" processing. EXITING. FIX."
+    source ./process_setup $CASE $TYPE
+    if [ $? -ne 0 ] ; then
+      echo "ERROR in setting up "$CASE" "$TYPE" processing. EXITING. FIX."
       exit 1
-    endif
+    fi
 #
-    cd ${procdir}
-    set yearnow = $yearbeg
-    while ( $yearnow <= $yearend )
-      set yrcheck = .done.${proccase}.${histnam}.${yearnow}
-      if !(-f ${yrcheck}) then
-        echo "Processing "${proccase}".${histnam}."${yearnow}" at "`date`
-        set msf = "${proccase}.${histnam}.${yearnow}-{01,02,03,04,05,06,07,08,09,10,11,12}.nc"
-        ./mss_read "${msshist}" "${msf}"
-        if ($status == 0) then
-          foreach i ( `ls ${proccase}.${histnam}.${yearnow}-??.nc`)
-            if ( $doesipcc != "0") then
-              ./create_ipcc_data $i
-              if ($status != 0) then
-                echo "Error from create_ipcc_data on file "${i}
-                exit 1
-              else
-                touch .ipcc.${i}
-              endif
-            endif
-            if ( $doesproc != "0") then
-              ./ccsm_var_split $i erase
-              if ($status != 0) then
-                echo "Error from ccsm_var_split on file "${i}
-                exit 1
-              else
-                touch .proc.${i}
-              endif
-            endif
-            if ((-f .proc.${i})||(-f .ipcc.${i})) touch .done.${i}
-          end
-        else
-          echo "Error from mss_read of "${msf}
+    cd $PROCDIR
+    YEARNOW=$YEARBEG
+    while [ $YEARNOW -le $YEAREND ] ; do
+      YRCHECK=.done.$PROCCASE.$HISTNAM.$YEARNOW
+      if [ ! -f $YRCHECK ] ; then
+        echo "Processing "$PROCCASE"."$HISTNAM"."$YEARNOW" at "`date`
+        MSFILES=$PROCCASE.$HISTNAM.$YEARNOW-{01,02,03,04,05,06,07,08,09,10,11,12}.nc
+        ./mss_read $MSSHIST $MSFILES
+        if [ $? -ne 0 ] ; then
+          echo "Error from mss_read of "$MSFILES
           exit 1
-        endif
-      endif
-      if (`ls .done.${proccase}.${histnam}.${yearnow}-??.nc | wc -l` == 12) then
-        touch ${yrcheck}
-        rm .????.${proccase}.${histnam}.${yearnow}-??.nc
-        if ( $doesipcc != "0") then
-          cd ${procdir}/IPCC
-          ./cf_var_ann_concat
-          cd ${procdir}
-        endif
-        if ( $doesproc != "0") then
-          foreach e (`ls -d *d.d`)
-            cd ${procdir}/${e}
-            ../var_mon_to_year
-            cd ${procdir}
-          end
-        endif
-      endif
-      @ yearnow = $yearnow + 1
-    end
+        else
+          for FILE in `ls $PROCCASE.$HISTNAM.$YEARNOW-??.nc` ; do
+            if [ $DO_IPCC -ne 0 ] ; then
+              ./create_ipcc_data $FILE
+              if [ $? -ne 0 ] ; then
+                echo "Error from create_ipcc_data on file "$FILE
+                exit 1
+              else
+                touch .ipcc.$FILE
+              fi
+            fi
+            if [ $DO_PROC -ne 0 ] ; then
+              ./var_split $FILE erase
+              if [ $? -ne 0 ] ; then
+                echo "Error from ccsm_var_split on file "$FILE
+                exit 1
+              else
+                touch .proc.$FILE
+              fi
+            fi
+            if [ -f .proc.$FILE ] || [-f .ipcc.$FILE ] ; then
+              touch .done.$FILE
+            fi
+          done
+        fi
+      fi
+      if [ `ls .done.$PROCCASE.$HISTNAM.$YEARNOW-??.nc | wc -l` -eq 12 ] ; then
+        touch $YRCHECK
+      fi
+      YEARNOW=`expr $YEARNOW + 1`
+    done
 #
-# Concatenate years -> decades, decades -> all
+# Concatenate months -> years, years -> decades, decades -> all
 #
-    ./finish_concatenation
+#    ./concatenate_data
 #
 # Store completed data on archival system
 #
     ./store_to_archive
 #
-  end # type
-end # case
+  cd $CURDIR
+  done # TYPE
+done # CASE
 #
 exit
diff --git a/create_ipcc_data b/create_ipcc_data
--- a/create_ipcc_data
+++ b/create_ipcc_data
@@ -1,39 +1,33 @@
-#!/bin/csh -f
+#!/bin/sh
 #
-if ("$#argv" == 0) then
-   echo "Usage: create_ipcc_data file"
-   exit 1
-else if ("$#argv" == 1) then
-   set file = $argv[1]
+if [ $# = 1 ] ; then
+   FILE=$1
 else
    echo "Usage: create_ipcc_data file"
    exit 1
-endif
+fi
 #
-if !(-f ${file}) then
+if [ ! -f $file] ; then
    echo $file "not found. Exit."
    exit 1
-endif
+fi
 #
 # Get correct NCL binary
 #
-set machine = `hostname`
-switch($machine)
- case "mineral*":                              # mineral @ CGD/NCAR
-    set ccps_ncl = /contrib/bin/ncl
-    setenv NCARG_ROOT /contrib/ncarg
-  breaksw
-  case "davinci*":                             # davinci @ NERSC
-    set ccps_ncl = /usr/common/usg/ncar/5.0.0/bin/ncl
-    setenv NCARG_ROOT /usr/common/usg/ncar/5.0.0
-  breaksw
-  case "lens*":                                # lens @ ORNL
-    set ccps_ncl = /ccs/home/wgstrand/bin/ncl
-    setenv NCARG_ROOT "/sw/analysis-x64/ncl/5.0.0/sl5.0_binary"
-  breaksw
-endsw
-#
-setenv CCPS_NCL ${ccps_ncl}
+case "$MACHINE" in
+  mineral* )                               # mineral @ CGD/NCAR
+    CCPS_NCL=/contrib/bin/ncl
+    NCARG_ROOT=/contrib/ncarg  ; export NCARG_ROOT ;;
+  davinci* )                               # davinci @ NERSC
+    CCPS_NCL=/usr/common/usg/ncar/5.0.0/bin/ncl
+    NCARG_ROOT=/usr/common/usg/ncar/5.0.0 ; export NCARG_ROOT ;;
+  lens* )                                  # lens @ ORNL
+    CCPS_NCL=/ccs/home/wgstrand/bin/ncl
+    NCARG_ROOT=/sw/analysis-x64/ncl/5.0.0/sl5.0_binary
+  * )
+    echo "Unable to run NCL from create_ipcc_data because "$MACHINE" not found."
+    exit 1 ;;
+esac
 #
 # Assume filename is of form bxx.xxxx.(pop|csim|clm2|cam2).hh.dddd-dd.nc
 # bxx.xx              : case name and number
@@ -41,72 +35,66 @@ setenv CCPS_NCL ${ccps_ncl}
 # hh                  : stream
 # dddd                : time period
 #
-set isES = `ls $file | cut -d"." -f3 | cut -c1-2 | uniq`
-if (${isES} == "ES") then
-  set f_case = 3 ; set f_comp = 4 ; set f_strm = 5 ; set f_tval = 6
+ISES=`ls $FILE | cut -d"." -f3 | cut -c1-2 | uniq`
+if [ $ISES == "ES"] ; then
+  FCASE=3 ; FCOMP=4 ; FSTRM=5 ; FTVAL=6
 else
-  set f_case = 2 ; set f_comp = 3 ; set f_strm = 4 ; set f_tval = 5
-endif
+  FCASE=2 ; FCOMP=3 ; FSTRM=4 ; FTVAL=5
+fi
 #
-set case = `echo ${file} | cut -d"." -f1-${f_case}`
-set comp = `echo ${file} | cut -d"." -f${f_comp}`
-set strm = `echo ${file} | cut -d"." -f${f_strm}`
-set tval = `echo ${file} | cut -d"." -f${f_tval}`
+CASE=`echo $FILE | cut -d"." -f1-$FCASE`
+COMP=`echo $FILE | cut -d"." -f$FCOMP`
+STRM=`echo $FILE | cut -d"." -f$FSTRM`
+TVAL=`echo $FILE | cut -d"." -f$FTVAL`
 #
-setenv FILE ${file}
-setenv CASE ${case}
-setenv TVAL ${tval}
+if [ ! -d ./IPCC] ; then
+   mkdir ./IPCC
+if
 #
-if !(-d IPCC) mkdir ./IPCC
-#
-if (${comp} == "cam2") then
-  if (${strm} == "h0") then
-    setenv COMP "atmm"
-    setenv NCL_SCPT atmm_2cf.ncl
-  else if (${strm} == "h1") then
-    setenv COMP "atmd"
-    setenv NCL_SCPT atmd_2cf.ncl
-  endif
-  ${CCPS_NCL} < ${NCL_SCPT}
-  if ($status != 0) then
+if [ $COMP == "cam2" ] ; then
+  if [ $STRM == "h0" ] ; then
+    COMP=atmm
+    NCL_SCPT=CCSM_atmm_2cf.ncl
+  elif [ $STRM == "h1" ] ; then
+    COMP=atmd
+    NCL_SCPT=atmd_2cf.ncl
+  fi
+  $CCPS_NCL < $NCL_SCPT
+  if [ $? -ne 0 ] ; then
      echo "NCL ERROR"
      exit 1
-  endif
-else if (${comp} == "clm2") then
-  setenv COMP "lndm"
-  setenv NCL_SCPT lndm_2cf.ncl
-  ${CCPS_NCL} < ${NCL_SCPT}
-  if ($status != 0) then
-     echo "NCL ERROR"
-     exit 1
-  endif
-else if (${comp} == "csim") then
-  ./regrid_data ${file}
-  @ f_tval = $f_tval + 1
-  setenv COMP "icem"
-  setenv NCL_SCPT icem_2cf.ncl
-  foreach file (`ls ${case}.csim.h.*.${tval}.nc`)
-    setenv FILE ${file}
-    set tval = `echo ${file} | cut -d"." -f${f_tval}`
-    setenv TVAL ${tval}
-    ${CCPS_NCL} < ${NCL_SCPT}
-    if ($status != 0) then
+  fi
+elif [ $comp == "clm2" ] ; then
+    COMP=lndm
+    NCL_SCPT=CCSM_lndm_2cf.ncl
+    $CCPS_NCL < $NCL_SCPT
+    if [ $? -ne 0 ] ; then
+      echo "NCL ERROR"
+      exit 1
+    fi
+elif [ $comp == "csim" ] ; then
+  ./regrid_data $file
+  FTVAL=`expr $FTVAL + 1`
+  COMP=icem
+  NCL_SCPT=CCSM_icem_2cf.ncl
+  for FILE in `ls $CASE.csim.h.*.*.nc` ; do
+    TVAL=`echo $file | cut -d"." -f$FTVAL`
+    $CCPS_NCL < $NCL_SCPT
+    if [ $? -ne 0 ] ; then
        echo "NCL ERROR"
        exit 1
-    endif
-  end
-else if (${comp} == "pop") then
-  @ f_tval = $f_tval + 1
-  set tval = `echo ${file} | cut -d"." -f${f_tval}`
-  setenv TVAL ${tval}
-  setenv COMP "ocnm"
-  setenv NCL_SCPT ocnm_2cf.ncl
-  ${CCPS_NCL} < ${NCL_SCPT}
-  if ($status != 0) then
+    fi
+  done
+elif [ $comp == "pop" ] ; then
+  FTVAL=`expr $FTVAL + 1`
+  TVAL=`echo $file | cut -d"." -f$FTVAL`
+  COMP=ocnm
+  NCL_SCPT=CCSM_ocnm_2cf.ncl
+  $CCPS_NCL < $NCL_SCPT
+  if [ $? -ne 0 ] ; then
      echo "NCL ERROR"
      exit 1
-  endif
-endif
-#
+  fi
+fi
 #
 exit
diff --git a/mss_write b/mss_write
--- a/mss_write
+++ b/mss_write
@@ -1,49 +1,55 @@
-#!/bin/csh -f
+#!/bin/sh
 # Write a file to a mass store
 #
 # Arguments:
 # 1 file to write
-# 2 place on mass store to write the file to
+# 2 directory on archival system to write file to
 #
-if ("$#argv" != 2) then
-  echo "Usage: mss_write file mss_directory - both REQUIRED"
-  exit 1
+if [ $# = 2 ] ; then
+  MSSF=$1
+  MSSD=$2
 else
-  set file = $argv[1]
-  if !(-f $file) then
-    echo "$file not present, cannot write to the mass store"
-    exit 1
-  endif
-  set mssd = $argv[2]
-endif
+  echo "I need two arguments:"
+  echo "1) file to write"
+  echo "2) directory on archival system to write file to"
+  exit 1
+fi
+#
+if [ ! -f $MSSF ] ; then
+  echo $MMSF" not present, cannot write to the archival system"
+  exit 1
+fi
+#
 #
 # If NCAR MSS msrcp command exists, use it.
-if (`which msrcp | wc -w` == 1 ) then
-  msrcp -pe 3652 -srcdelete $file mss:${mssd}/${file}
-  if ($status == 0) then
-    echo ${file}" written to "${mssd}" and erased."
+if [ `which msrcp` ] ; then
+  msrcp -pe 3652 -srcdelete $MSSF "mss:${MSSD}/${MSSF}"
+  if [ $? -eq 0 ] ; then
+    echo $MSSF" written to "${MSSD}/${MSSF}" and erased."
   else
-    echo "Problem with storing "${file}" to "${mssd}". Stopping."
+    echo "Problem with storing "${MSSF}" to "${MSSD}". Stopping."
     exit 1
-  endif
-endif
+  fi
+else
 #
 # If NERSC/ORNL hsi command exists, use it.
-if ( `which hsi | wc -w` == 1  ) then 
-  hsi -q "mkdir -m 775 -p ${mssd} ; put -U ${mssd}/${file}" >& /dev/null
-  if ($status == 0) then
-    echo ${file}" written to "${mssd}" and erased."
-    rm -f ${file}
-  else
-    hsi -q "put ${file}" >& /dev/null
-    if ($status == 0) then
-      echo ${file}" written to your HPSS HOME and erased."
-      rm -f ${file}
-    else
-      echo "Problem with HPSS on "${file}". Stopping"
-      exit 1
-    endif
-  endif
-endif
-#
-exit
+   if [ `which hsi` ] ; then 
+     hsi -q "mkdir -m 775 -p $MSSD ; put -U ${MSSD}/${MSSF}" >& /dev/null
+     if [ $? -eq 0 ] ; then
+       echo ${MSSF}" written to "${MSSD}" and erased."
+       rm -f $MSSF
+     else
+       hsi -q "put ${MSSF}" >& /dev/null
+       if [ $? -eq 0 ] ; then
+         echo ${MSSF}" written to your HPSS HOME and erased."
+         rm -f $MSSF
+       else
+         echo "Problem with HPSS on "${MSSF}". Stopping"
+         exit 1
+       fi
+     fi      
+   else
+     echo "Neither msrcp nor hsi exist."
+     exit 1
+  fi
+fi
diff --git a/process_setup b/process_setup
--- a/process_setup
+++ b/process_setup
@@ -1,263 +1,249 @@
-#!/bin/csh -f
+#!/bin/sh
 #
 # Set up a bunch of stuff
 #
-if ("$#argv" != 4) then
-  echo "Usage: process_setup CASE type do_proc do_ipcc"
+if [ $# = 2 ] ; then
+  PROCCASE=$1
+  PROCTYPE=$2
+else
+  echo "Usage: process_setup case type"
   echo "Type must be one of (atmm atmd lndm ocnm icem)"
   exit 1
-else
-  set proccase = $argv[1]
-  set proctype = $argv[2]
-  set doesproc = $argv[3]
-  set doesipcc = $argv[4]
-endif
+fi
 #
-if (${proctype} != "atmm") then
-  if (${proctype} != "atmd") then
-    if (${proctype} != "lndm") then
-      if (${proctype} != "ocnm") then
-        if (${proctype} != "icem") then
-          echo "Usage: process_setup CASE type"
+if [ $PROCTYPE != "atmm" ] ; then
+  if [ $PROCTYPE != "atmd" ] ; then
+    if [ $PROCTYPE != "lndm" ] ; then
+      if [ $PROCTYPE != "ocnm" ] ; then
+        if [ $PROCTYPE != "icem" ] ; then
+          echo "Usage: process_setup case type"
           echo "Type must be one of (atmm atmd lndm ocnm icem)"
           exit 1
-        endif
-      endif
-    endif
-  endif
-endif
+        fi
+      fi
+    fi
+  fi
+fi
 #
 # Extract information from "experiments.txt"
 #
-set location = `egrep "^${proccase} " experiments.txt | cut -c20-  | cut -d" " -f1`
-set descrip  = `egrep "^${proccase} " experiments.txt | cut -c25-  | cut -d" " -f1`
-set parent   = `egrep "^${proccase} " experiments.txt | cut -c50-  | cut -d" " -f1`
-set branch   = `egrep "^${proccase} " experiments.txt | cut -c65-  | cut -d" " -f1`
-set yearbeg  = `egrep "^${proccase} " experiments.txt | cut -c80-  | cut -d" " -f1`
-set yearend  = `egrep "^${proccase} " experiments.txt | cut -c85-  | cut -d" " -f1`
-set histbase = `egrep "^${proccase} " experiments.txt | cut -c100- | cut -d" " -f1`
+if [ -f ./experiments.txt ] ; then
+  LOCATION=`egrep "^$PROCCASE " experiments.txt | cut -c20-  | cut -d" " -f1`
+   DESCRIP=`egrep "^$PROCCASE " experiments.txt | cut -c25-  | cut -d" " -f1`
+    PARENT=`egrep "^$PROCCASE " experiments.txt | cut -c50-  | cut -d" " -f1`
+    BRANCH=`egrep "^$PROCCASE " experiments.txt | cut -c65-  | cut -d" " -f1`
+   YEARBEG=`egrep "^$PROCCASE " experiments.txt | cut -c80-  | cut -d" " -f1`
+   YEAREND=`egrep "^$PROCCASE " experiments.txt | cut -c85-  | cut -d" " -f1`
+  HISTBASE=`egrep "^$PROCCASE " experiments.txt | cut -c100- | cut -d" " -f1`
+else
+  echo "Cannot find experiments.txt. HELP"
+  exit 1
+fi
+DEFINED=`/usr/bin/printenv | grep -c '^LOCATION='`
+if ! [ $DEFINED ] ; then
+  echo "Unable to set variables because "$PROCCASE" not found in experiments.txt"
+  exit 1
+fi
 #
-set decdbeg  = `echo $yearbeg | cut -c1-3`
-set decdend  = `echo $yearend | cut -c1-3`
-@ decount    = ($decdend - $decdbeg) + 1
-@ mncount    = (($yearend - $yearbeg) + 1) * 12
+DECDBEG=`echo $YEARBEG | cut -c1-3`
+DECDEND=`echo $YEAREND | cut -c1-3`
+DECOUNT=`expr '(' $DECDEND '-' $DECDBEG ')' '+' '1'`
+MNCOUNT=`expr '(' '(' $YEAREND '-' $YEARBEG ')' '+' '1' ')' '*' '12'`
 #
 # Processed data archival locations
 #
-switch($location)
-  case "NC":                                        # NCAR experiments
-    set mssbase = /CCSM/csm/${proccase}
-    set machine = "mineral"
-  breaksw
-  case "NE":                                        # NERSC experiments
-    set mssbase = /nersc/mp9/strandwg/CCSM/csm/${proccase}
-    set machine = "davinci"
-  breaksw
-  case "OR":                                        # ORNL experiments
-    set mssbase = /f2/wgstrand/CCSM/csm/${proccase}
-    set machine = "lens0"
-  breaksw
-  default:
-    echo "Unable to set mssbase because "${proccase}" not found in experiments.txt"
-    exit 1
-  breaksw
-endsw
+case "$LOCATION" in
+  NC )                                        # NCAR experiments
+    MSSBASE=/CCSM/csm/$PROCCASE
+    MACHINE="mineral"  ;;
+  NE )                                        # NERSC experiments
+    MSSBASE=/nersc/mp9/strandwg/CCSM/csm/$PROCCASE
+    MACHINE="davinci"  ;;
+  OR )                                        # ORNL experiments
+    MSSBASE=/f2/wgstrand/CCSM/csm/$PROCCASE
+    MACHINE="lens0"    ;;
+  * )
+    echo "Unable to set variables because "$LOCATION" not found in experiments.txt"
+    exit 1 ;;
+esac
 #
 # History tape locations
 #
-switch($proctype)
-  case "atmm":
-    set histnam = "cam2.h0"
-    set msshist = ${histbase}/${proccase}/atm/hist
-    set mssipcc = ${mssbase}/atm/ipcc/tseries/monthly
-    set mssproc = ${mssbase}/atm/proc/tseries/monthly
-  breaksw
-  case "atmd": 
-    set histnam = "cam2.h1"
-    set msshist = ${histbase}/${proccase}/atm/hist
-    set mssipcc = ${mssbase}/atm/ipcc/tseries/daily
-    set mssproc = ${mssbase}/atm/proc/tseries/daily
-  breaksw
-  case "lndm": 
-    set histnam = "clm2.h0"
-    set msshist = ${histbase}/${proccase}/lnd/hist
-    set mssipcc = ${mssbase}/lnd/ipcc/tseries/daily
-    set mssproc = ${mssbase}/lnd/proc/tseries/daily
-  breaksw
-  case "ocnm": 
-    set histnam = "pop.h"
-    set msshist = ${histbase}/${proccase}/ocn/hist
-    set mssipcc = ${mssbase}/ocn/ipcc/tseries/monthly
-    set mssproc = ${mssbase}/ocn/proc/tseries/monthly
-  breaksw
-  case "icem": 
-    set histnam = "csim.h"
-    set msshist = ${histbase}/${proccase}/ice/hist
-    set mssipcc = ${mssbase}/ice/ipcc/tseries/monthly
-    set mssproc = ${mssbase}/ice/proc/tseries/monthly
-  breaksw
-endsw
+case "$PROCTYPE" in
+  atmm )
+    HISTNAM="cam2.h0"
+    MSSHIST=$HISTBASE/$PROCCASE/atm/hist
+    MSSIPCC=$MSSBASE/atm/ipcc/tseries/monthly
+    MSSPROC=$MSSBASE/atm/proc/tseries/monthly  ;;
+  atmd )
+    HISTNAM="cam2.h1"
+    MSSHIST=$HISTBASE/$PROCCASE/atm/hist
+    MSSIPCC=$MSSBASE/atm/ipcc/tseries/daily
+    MSSPROC=$MSSBASE/atm/proc/tseries/daily    ;;
+  lndm ) 
+    HISTNAM="clm2.h0"
+    MSSHIST=$HISTBASE/$PROCCASE/lnd/hist
+    MSSIPCC=$MSSBASE/lnd/ipcc/tseries/daily
+    MSSPROC=$MSSBASE/lnd/proc/tseries/daily    ;;
+  ocnm ) 
+    HISTNAM="pop.h"
+    MSSHIST=$HISTBASE/$PROCCASE/ocn/hist
+    MSSIPCC=$MSSBASE/ocn/ipcc/tseries/monthly
+    MSSPROC=$MSSBASE/ocn/proc/tseries/monthly  ;;
+  icem ) 
+    HISTNAM="csim.h"
+    MSSHIST=$HISTBASE/$PROCCASE/ice/hist
+    MSSIPCC=$MSSBASE/ice/ipcc/tseries/monthly
+    MSSPROC=$MSSBASE/ice/proc/tseries/monthly  ;;
+  * ) 
+    echo "Unable to continue because "$PROCTYPE" not known."
+    exit 1 ;;
+esac
 #
 # resolve machine/site dependencies
 #
-switch($machine)
-  case "mineral*":                                # mineral @ CGD/NCAR
-    set basedir  = /home/strandwg/data/CCP_Processing_Suite
-    switch($proctype)
-      case "atmm": 
-        set procdir = /datalocal/ccpc/$USER/${proccase}/atm/mon
-      breaksw
-      case "atmd": 
-        set procdir = /datalocal/ccpc/$USER/${proccase}/atm/day
-      breaksw
-      case "lndm": 
-        set procdir = /datalocal/ccpc/$USER/${proccase}/lnd/mon
-      breaksw
-      case "ocnm": 
-        set procdir = /datalocal/ccpc/$USER/${proccase}/ocn/mon
-        set regrdir = /project/ccr/strandwg/IPCC_Processing/ocn/CCSM
-        set oregrid = ${basedir}/regridding/ccsm_ocn_rgd.mineral
-        if !(-f ${oregrid}) then
+case "$MACHINE" in 
+  mineral* )                                # mineral @ CGD/NCAR
+    BASEDIR=/home/strandwg/data/CCP_Processing_Suite
+    CCPS_NCKS=/usr/local/bin/ncks ; export CCPS_NCKS
+    CCPS_NCRCAT=/usr/local/bin/ncrcat ; export CCPS_NCRCAT
+    case "$PROCTYPE" in
+      atmm ) PROCDIR=/datalocal/ccpg/$USER/$PROCCASE/atm/mon ;;
+      atmd ) PROCDIR=/datalocal/ccpg/$USER/$PROCCASE/atm/day ;;
+      lndm ) PROCDIR=/datalocal/ccpg/$USER/$PROCCASE/lnd/mon ;;
+      ocnm ) 
+        PROCDIR=/datalocal/ccpg/$USER/$PROCCASE/ocn/mon
+        REGRDIR=/project/ccr/strandwg/IPCC_Processing/ocn/CCSM
+        OREGRID=$BASEDIR/regridding/ccsm_ocn_rgd.mineral
+        if [ ! -f $OREGRID ] ; then
           echo "Need to build OCN regridding code. Do that and re-run."
           exit 1
-        else
-          setenv CCSM_OCN_RGD $oregrid
-        endif
-      breaksw
-      case "icem": 
-        set procdir = /datalocal/ccpc/$USER/${proccase}/ocn/mon
-        set regrdir = /project/ccr/strandwg/IPCC_Processing/ice/CCSM
-        set iregrid = ${basedir}/regridding/ccsm_ice_rgd.mineral
-        if !(-f ${iregrid}) then
+        fi ;;
+      icem ) 
+        PROCDIR=/datalocal/ccpg/$USER/$PROCCASE/ocn/mon
+        REGRDIR=/project/ccr/strandwg/IPCC_Processing/ice/CCSM
+        IREGRID=$BASEDIR/regridding/ccsm_ice_rgd.mineral
+        if [ ! -f $IREGRID ] ; then
           echo "Need to build ICE regridding code. Do that and re-run."
           exit 1
-        else
-          setenv CCSM_ICE_RGD $iregrid
-         endif
-      breaksw
-   endsw
-   breaksw
+        fi ;;
+      * ) 
+        echo "Unable to continue because "$PROCTYPE" not known."
+        exit 1 ;;
+    esac ;;
 
-   case "davinci*":                                # davinci @ NERSC
-    set basedir     = /usr/common/homes/s/strandwg/CCP_Processing_Suite
-    set ccps_ncks   = /usr/common/homes/s/strandwg/bin/ncks
-    set ccps_ncrcat = /usr/common/homes/s/strandwg/bin/ncrcat
-    switch($proctype)
-      case "atmm": 
-        set procdir = /scratch/scratchdirs/$USER/${proccase}/atm/mon
-      breaksw
-      case "atmd": 
-        set procdir = /scratch/scratchdirs/$USER/${proccase}/atm/day
-      breaksw
-      case "lndm": 
-        set procdir = /scratch/scratchdirs/$USER/${proccase}/lnd/mon
-      breaksw
-      case "ocnm": 
-        set procdir = /scratch/scratchdirs/$USER/${proccase}/ocn/mon
-        set regrdir = /project/projectdirs/ccp/CCP_Processing_Suite/ocn/CCSM
-        set oregrid = ${basedir}/regridding/ccsm_ocn_rgd.davinci
-        if !(-f ${oregrid}) then
+  davinci* )                                # davinci @ NERSC
+    BASEDIR=/usr/common/homes/s/strandwg/CCP_Processing_Suite
+    CCPS_NCKS=/usr/common/homes/s/strandwg/bin/ncks ; export CCPS_NCKS
+    CCPS_NCRCAT=/usr/common/homes/s/strandwg/bin/ncrcat ; export CCPS_NCRCAT
+    case "$PROCTYPE" in
+      atmm ) PROCDIR=/scratch/scratchdirs/$USER/$PROCCASE/atm/mon ;;
+      atmd ) PROCDIR=/scratch/scratchdirs/$USER/$PROCCASE/atm/day ;;
+      lndm ) PROCDIR=/scratch/scratchdirs/$USER/$PROCCASE/lnd/mon ;;
+      ocnm ) 
+        PROCDIR=/scratch/scratchdirs/$USER/$PROCCASE/ocn/mon
+        REGRDIR=/project/projectdirs/ccp/CCP_Processing_Suite/ocn/CCSM
+        OREGRID=$BASEDIR/regridding/ccsm_ocn_rgd.davinci
+        if [ ! -f $OREGRID ] ; then
           echo "Need to build OCN regridding code. Do that and re-run."
           exit 1
-        else
-          setenv CCSM_OCN_RGD $oregrid
-        endif
-      breaksw
-      case "icem": 
-        set procdir = /scratch/scratchdirs/$USER/${proccase}/ice/mon
-        set regrdir = /project/projectdirs/ccp/CCP_Processing_Suite/ice/CCSM
-        set iregrid = ${basedir}/regridding/ccsm_ice_rgd.davinci
-        if !(-f ${iregrid}) then
+        fi ;;
+      icem ) 
+        procdir=/scratch/scratchdirs/$USER/$PROCCASE/ice/mon
+        regrdir=/project/projectdirs/ccp/CCP_Processing_Suite/ice/CCSM
+        iregrid=$BASEDIR/regridding/ccsm_ice_rgd.davinci
+        if [ ! -f $IREGRID ] ; then
           echo "Need to build ICE regridding code. Do that and re-run."
           exit 1
         else
-          setenv CCSM_ICE_RGD $iregrid
-         endif
-      breaksw
-    endsw
-  breaksw
+          setenv CCSM_ICE_RGD $IREGRID
+         fi ;;
+      * ) 
+        echo "Unable to continue because "$PROCTYPE" not known."
+        exit 1 ;;
+    esac ;;
 
-  case "lens*":                                # lens @ ORNL
-    set basedir     = /ccs/home/wgstrand/CCP_Processing_Suite
-    set ccps_ncks   = /ccs/home/wgstrand/bin/ncks
-    set ccps_ncrcat = /ccs/home/wgstrand/bin/ncrcat
-    switch($proctype)
-      case "atmm": 
-        set procdir = /tmp/work/$USER/${proccase}/atm/mon
-      breaksw
-      case "atmd": 
-        set procdir = /tmp/work/$USER/${proccase}/atm/day
-      breaksw
-      case "lndm": 
-        set procdir = /tmp/work/$USER/${proccase}/lnd/mon
-      breaksw
-      case "ocnm": 
-        set procdir = /tmp/work/$USER/${proccase}/ocn/mon
-        set regrdir = /f2/wgstrand/CCP_Processing_Suite/ocn/CCSM
-        set oregrid = ${basedir}/regridding/ccsm_ocn_rgd.lens0
-        if !(-f ${oregrid}) then
+  lens* )                                # lens @ ORNL
+    BASEDIR=/ccs/home/wgstrand/CCP_Processing_Suite
+    CCPS_NCKS=/ccs/home/wgstrand/bin/ncks ; export CCPS_NCKS
+    CCPS_NCRCAT=/ccs/home/wgstrand/bin/ncrcat ; export CCPS_NCRCAT
+    case "$PROCTYPE" in
+      atmm ) PROCDIR=/tmp/work/$USER/$PROCCASE/atm/mon ;;
+      atmd ) PROCDIR=/tmp/work/$USER/$PROCCASE/atm/day ;;
+      lndm ) PROCDIR=/tmp/work/$USER/$PROCCASE/lnd/mon ;;
+      ocnm ) 
+        procdir=/tmp/work/$USER/$PROCCASE/ocn/mon
+        regrdir=/f2/wgstrand/CCP_Processing_Suite/ocn/CCSM
+        oregrid=$BASEDIR/regridding/ccsm_ocn_rgd.lens0
+        if [ ! -f $OREGRID ] ; then
           echo "Need to build OCN regridding code. Do that and re-run."
           exit 1
-        else
-          setenv CCSM_OCN_RGD $oregrid
-        endif
-      breaksw
-      case "icem": 
-        set procdir = /tmp/work/$USER/${proccase}/ice/mon
-        set regrdir = /f2/wgstrand/CCP_Processing_Suite/ocn/CCSM
-        set iregrid = ${basedir}/regridding/ccsm_ice_rgd.lens0
-        if !(-f ${iregrid}) then
+        fi ;;
+      icem ) 
+        procdir=/tmp/work/$USER/$PROCCASE/ice/mon
+        regrdir=/f2/wgstrand/CCP_Processing_Suite/ocn/CCSM
+        iregrid=$BASEDIR/regridding/ccsm_ice_rgd.lens0
+        if [ ! -f $IREGRID ] ; then
           echo "Need to build ICE regridding code. Do that and re-run."
           exit 1
-        else
-          setenv CCSM_ICE_RGD $iregrid
-         endif
-      breaksw
-   endsw
-   breaksw
-endsw
+        fi ;;
+      * ) 
+        echo "Unable to continue because "$PROCTYPE" not known."
+        exit 1 ;;
+    esac ;;
+  * ) 
+    echo "Unable to continue because "$MACHINE" not known."
+    exit 1 ;;
+esac
 #
 # Print out values
 #
 echo " process_setup as of : "`date`
 echo ""
-echo "           Case name : "${proccase}
-echo "     Processing type : "${proctype}
-echo "            Location : "${location}
-echo "         Description : "${descrip}
-echo "         Parent case : "${parent}
-echo "         Branch date : "${branch}
-echo "          Begin year : "${yearbeg}
-echo "            End year : "${yearend}
-echo "        Months count : "${mncount}
-echo "        Decade count : "${decount}
+echo "           Case name : "$PROCCASE ; export PROCCASE
+echo "     Processing type : "$PROCTYPE ; export PROCTYPE
+echo "            Location : "$LOCATION ; export LOCATION
+echo "         Description : "$DESCRIP  ; export DESCRIP
+echo "         Parent case : "$PARENT   ; export PARENT
+echo "         Branch date : "$BRANCH   ; export BRANCH
+echo "          Begin year : "$YEARBEG  ; export YEARBEG
+echo "            End year : "$YEAREND  ; export YEAREND
+echo "        Months count : "$MNCOUNT  ; export MNCOUNT
+echo "        Decade count : "$DECOUNT  ; export DECOUNT
 echo ""
-echo "       History files : "${msshist}
-echo "       History names : "${histnam}
-echo "   IPCC format files : "${mssipcc}
-echo "     Processed files : "${mssproc}
+echo "       History files : "$MSSHIST  ; export MSSHIST
+echo "       History names : "$HISTNAM  ; export HISTNAM
+echo "   Archival base dir : "$MSSBASE  ; export MSSBASE
+echo "   IPCC format files : "$MSSIPCC  ; export MSSIPCC
+echo "     Processed files : "$MSSPROC  ; export MSSPROC
 echo ""
-echo "      Processing dir : "${procdir}
+echo "     Processing host : "$MACHINE  ; export MACHINE
+echo "      Processing dir : "$PROCDIR  ; export PROCDIR
+echo " Processing code dir : "$BASEDIR  ; export BASEDIR
 #  
-if !(-d ${procdir}) mkdir -p ${procdir}
-cd ${procdir}
+if [ ! -d $PROCDIR ] ; then 
+  mkdir -p $PROCDIR 
+fi
+cd $PROCDIR
 #
-if ( $doesipcc != "0") then
-  setenv PARENT $parent
-  setenv BRANCH $branch
-  if !(-d  ${procdir}/IPCC) mkdir -p ${procdir}/IPCC
-  ln -s -f ${basedir}/create_ipcc_data    .
-  ln -s -f ${basedir}/CCSM_${proctype}_2cf.ncl   .
-  ln -s -f ${basedir}/attributes_ccsm.ncl .
-  cd ${procdir}/IPCC
-  ln -s -f ${basedir}/mss_*      .
-  ln -s -f ${basedir}/cf_*concat .
-  cd ${procdir}
-endif
+if [ $DO_IPCC ] ; then
+  if [ ! -d $PROCDIR/IPCC ] ; then
+     mkdir -p $PROCDIR/IPCC
+  fi
+  ln -s -f $BASEDIR/create_ipcc_data    .
+  ln -s -f $BASEDIR/CCSM_${PROCTYPE}_2cf.ncl   .
+  ln -s -f $BASEDIR/attributes_ccsm.ncl .
+  cd $PROCDIR/IPCC
+  ln -s -f $BASEDIR/mss_*      .
+  ln -s -f $BASEDIR/cf_*concat .
+  cd $PROCDIR
+fi
 #
-if ( $doesproc != "0") then
-  ln -s -f ${basedir}/mss_* .
-  ln -s -f ${basedir}/var_* .
-endif
+if [ $DO_PROC ] ; then
+  ln -s -f $BASEDIR/mss_* .
+  ln -s -f $BASEDIR/var_* .
+fi
 #
-exit
+ln -s -f $BASEDIR/finish_concatenation .
+ln -s -f $BASEDIR/store_to_archive     .
+#
diff --git a/var_dec_to_all b/var_dec_to_all
--- a/var_dec_to_all
+++ b/var_dec_to_all
@@ -1,126 +1,104 @@
-#!/bin/csh -f
+#!/bin/sh
 #
 # Concatenate decades of by-field CCSM netCDF into whole span
 #
-if ("$#argv" != 0) then
-   echo "Usage: var_dec_to_all"
-   echo "Can use DECCOUNT as defined by process_setup"
-   exit 1
-endif
+if [ $# -ne 0 ] ; then
+  echo "Usage: var_mon_to_year"
+  echo "Can use DECOUNT as defined by process_setup"
+  exit 1
+fi
 #
-# Get correct NCO binaries
-#
-set machine = `hostname`
-switch($machine)
-  case "mineral*":                                # mineral @ CGD/NCAR
-    set ccps_ncks   = /usr/local/bin/ncks
-    set ccps_ncrcat = /usr/local/bin/ncrcat
-  breaksw
-  case "davinci*":                                # davinci @ NERSC
-    set ccps_ncks   = /usr/common/homes/s/strandwg/bin/ncks
-    set ccps_ncrcat = /usr/common/homes/s/strandwg/bin/ncrcat
-  breaksw
-  case "lens*":                                # lens @ ORNL
-    set ccps_ncks   = /ccs/home/wgstrand/bin/ncks
-    set ccps_ncrcat = /ccs/home/wgstrand/bin/ncrcat
-  breaksw
-endsw
-#
-setenv CCPS_NCKS   ${ccps_ncks}
-setenv CCPS_NCRCAT ${ccps_ncrcat}
-#
-set chek = `ls b*.*.h*.*.*cat*.nc | cut -d"." -f3 | cut -c1-2 | uniq`
-foreach m ( ${chek} )
-  if (${m} == "ES") then
-    set fc = 3 ; set fv = 6 ; set ft = 7 ; set fd = 4 ; set fe = 5
+CHEK=`ls b*.*.h*.*.*cat*.nc | cut -d"." -f3 | cut -c1-2 | uniq`
+for m in $CHEK ; do
+  if [ $m = "ES" ] ; then
+    FC=3 ; FV=6 ; FT=7 ; FD=4 ; FE=5
   else
-    set fc = 2 ; set fv = 5 ; set ft = 6 ; set fd = 3 ; set fe = 4
-  endif
-  set comp = `ls b*.*.*.h*.*.*cat*.nc | cut -d"." -f${fd}-${fe} | uniq`
-  foreach p (`echo ${comp}`)
-    set vars = `ls b*.*.${p}.*.*cat*.nc | cut -d"." -f${fv} | uniq`
-    foreach v (`echo ${vars}`)
-      set cases = `ls b*.${p}.${v}.*cat*.nc | cut -d"." -f1-${fc} | uniq`
-      foreach c (`echo ${cases}`)
-        if ( $?deccount ) then
-          if (${p} == "cam2.h1") then
-            set num = `ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | wc -l`
-            if (${num} == ${deccount}) then
-              set y0 = `ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${ft} | cut -c1-4`
-              set y1 = `ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${ft} | cut -c16-19`
-              set df = ${c}.${p}.${v}.${y0}-01-01_allcat_${y1}-12-31.nc
-              $CCPS_NCRCAT -h -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc ${df}
-              if ($status == 0) then
+    FC=2 ; FV=5 ; FT=6 ; FD=3 ; FE=4
+  fi
+  COMP=`ls b*.*.*.h*.*.*cat*.nc | cut -d"." -f${FD}-${FE} | uniq`
+  for p in $COMP ; do
+    VARS=`ls b*.*.${p}.*.*cat*.nc | cut -d"." -f${FV} | uniq`
+    for v in $VARS ; do
+      CASES=`ls b*.${p}.${v}.*cat*.nc | cut -d"." -f1-${FC} | uniq`
+      for c in $CASES ; do
+        if [ $DECOUNT ] ; then
+          echo "Concatenating of "${c}"."${p}"."${v}" files and checking decade counts: "$DECOUNT
+          if [ $p = "cam2.h1" ] ; then
+            NUM=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | wc -l`
+            if [ $NUM = $DECOUNT ] ; then
+              Y0=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
+              Y1=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${FT} | cut -c16-19`
+              DF=${c}.${p}.${v}.${Y0}-01-01_allcat_${Y1}-12-31.nc
+              $CCPS_NCRCAT -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc $DF
+              if [ $? = 0 ] ; then
                 rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
-                set tf = ${c}.${p}.${v}.${y0}-01-01_cat_${y1}-12-31.nc
-                mv ${df} ${tf}
-                echo "Completed "${tf}
+                TF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
+                mv $DF $TF
+                echo "Completed "$TF
               else
-                echo "Failure on concat of "${c}"."${p}"."${v}".etc files"
+                echo "Failure on concat of "${c}"."${p}"."${v}" files"
                 exit 1
-              endif
+              fi
             else
-              echo "Missing decade(s) from "${c}"."${p}"."${v}".etc files"
-              echo "Count is "${num}" should be "${deccount}
+              echo "Missing decade(s) from "${c}"."${p}"."${v}" files"
+              echo "Count is "$NUM" should be "$DECOUNT
               exit 1
-            endif
+            fi
           else
-            set num = `ls ${c}.${p}.${v}.????-01_cat_????-12.nc | wc -l`
-            if (${num} == ${deccount}) then
-              set y0 = `ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${ft} | cut -c1-4`
-              set y1 = `ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${ft} | cut -c13-16`
-              set df = ${c}.${p}.${v}.${y0}-01-01_allcat_${y1}-12-31.nc
-              $CCPS_NCRCAT -h -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc ${df}
-              if ($status == 0) then
-                rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
-                set tf = ${c}.${p}.${v}.${y0}-01-01_cat_${y1}-12-31.nc
-                mv ${df} ${tf}
-                echo "Completed "${tf}
+            NUM=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | wc -l`
+            if [ $NUM = $DECOUNT ] ; then
+              Y0=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
+              Y1=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${FT} | cut -c13-16`
+              DF=${c}.${p}.${v}.${Y0}-01-allcat_${Y1}-12.nc
+              $CCPS_NCRCAT -O ${c}.${p}.${v}.????-01_cat_????-12.nc $DF
+              if [ $? = 0 ] ; then
+                rm -f ${c}.${p}.${v}.????-01_cat_????-12.nc
+                TF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
+                mv $DF $TF
+                echo "Completed "$TF
               else
-                echo "Failure on concat of "${c}"."${p}"."${v}".etc files"
+                echo "Failure on concat of "${c}"."${p}"."${v}" files"
                 exit 1
-              endif
+              fi
             else
-              echo "Missing decade(s) from "${c}"."${p}"."${v}".etc files"
-              echo "Count is "${num}" should be "${deccount}
+              echo "Missing decade(s) from "${c}"."${p}"."${v}" files"
+              echo "Count is "$NUM" should be "$DECOUNT
               exit 1
-            endif
-          endif
+            fi
+          fi
         else
-          echo "Concatenating of "${c}"."${p}"."${v}".etc files WITHOUT checking counts." 
-          if (${p} == "cam2.h1") then
-            set y0 = `ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${ft} | cut -c1-4`
-            set y1 = `ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${ft} | cut -c16-19`
-            set df = ${c}.${p}.${v}.${y0}-01-01_allcat_${y1}-12-31.nc
-            $CCPS_NCRCAT -h -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc ${df}
-            if ($status == 0) then
+          echo "Concatenating of "${c}"."${p}"."${v}" files WITHOUT checking counts." 
+          if [ $p = "cam2.h1" ] ; then
+            Y0=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
+            Y1=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${FT} | cut -c16-19`
+            DF=${c}.${p}.${v}.${Y0}-01-01_allcat_${Y1}-12-31.nc
+            $CCPS_NCRCAT -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc $DF
+            if [ $? = 0 ] ; then
               rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
-              set tf = ${c}.${p}.${v}.${y0}-01-01_cat_${y1}-12-31.nc
-              mv ${df} ${tf}
-              echo "Completed "${tf}
+              TF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
+              mv $DF $TF
+              echo "Completed "$TF
             else
-              echo "Failure on concat of "${c}"."${p}"."${v}".etc files"
+              echo "Failure on concat of "${c}"."${p}"."${v}" files"
               exit 1
-            endif
+            fi
           else
-            set y0 = `ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${ft} | cut -c1-4`
-            set y1 = `ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${ft} | cut -c13-16`
-            set df = ${c}.${p}.${v}.${y0}-01-01_allcat_${y1}-12-31.nc
-            $CCPS_NCRCAT -h -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc ${df}
-            if ($status == 0) then
-              rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
-              set tf = ${c}.${p}.${v}.${y0}-01-01_cat_${y1}-12-31.nc
-              mv ${df} ${tf}
-              echo "Completed "${tf}
+            Y0=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
+            Y1=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${FT} | cut -c13-16`
+            DF=${c}.${p}.${v}.${Y0}-01_allcat_${Y1}-12.nc
+            $CCPS_NCRCAT -O ${c}.${p}.${v}.????-01_cat_????-12.nc ${DF}
+            if [ $? = 0 ] ; then
+              rm -f ${c}.${p}.${v}.????-01_cat_????-12.nc
+              TF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
+              mv $DF $TF
+              echo "Completed "$TF
             else
-              echo "Failure on concat of "${c}"."${p}"."${v}".etc files"
+              echo "Failure on concat of "${c}"."${p}"."${v}" files"
               exit 1
-            endif
-          endif
-        endif
-      end
-    end
-  end
-end
-#
-exit
+            fi
+          fi
+        fi
+      done
+    done
+  done
+done
