Added BRCP45 to process_le5_template

diff --git a/process_le5_template b/process_le5_template
--- a/process_le5_template
+++ b/process_le5_template
@@ -60,7 +60,7 @@ case "$PROCHOST" in
     if [ `echo $CASE | cut -d"." -f3 | cut -c1-6` = "BRCP45" ] ; then
       LOCALDSK=/glade/p/ncgd0014/medens/archive/$CASE ; export LOCALDSK
       ARCHIVE_BASE=/CCSM/csm/CESM-CAM5-BGC-ME      ; export ARCHIVE_BASE
-      DISK_BASE=/glade/p/cesm0005/CESM-CAM5-BGC-ME ; export DISK_BASE
+      DISK_BASE=/glade/p/ncgd0014/CESM-CAM5-BGC-ME ; export DISK_BASE
     else
       LOCALDSK=/glade/p/cesm0005/csm/$CASE         ; export LOCALDSK
       ARCHIVE_BASE=/CCSM/csm/CESM-CAM5-BGC-LE      ; export ARCHIVE_BASE
@@ -427,47 +427,54 @@ else
   fi
 fi
 #
-# Move completed data on to DISK_PROC
+# Move completed data on to DISK_PROC, not for RCP4.5 runs
 #
-echo -n "TS disk move start: " ; date
-if [ "$TPER" = "hr6" ] ; then
-  if [ "$EXPTYP" = "RCP" ] ; then
-    OUTTIME=2026010100Z-2035123118Z ; export OUTTIME
+if [ `echo $CASE | cut -d"." -f3 | cut -c1-6` = "BRCP45" ] ; then
+  ./update_status complete
+  echo -n "TS COMPLETE: " ; date
+else
+  echo -n "TS disk move start: " ; date
+  if [ "$TPER" = "hr6" ] ; then
+    if [ "$EXPTYP" = "RCP" ] ; then
+      OUTTIME=2026010100Z-2035123118Z ; export OUTTIME
+      ./disk_move_var
+      if [ $? -ne 0 ] ; then
+        echo "disk_move failed"
+        ./update_status error "$CASE $HIST $TPER"
+        exit 1
+      else
+        OUTTIME=2071010100Z-2080123118Z ; export OUTTIME
+        ./disk_move_var
+        if [ $? -ne 0 ] ; then
+           echo "disk_move failed"
+          ./update_status error "$CASE $HIST $TPER"
+          exit 1
+        else
+          echo -n "TS disk_move end: " ; date
+        fi
+      fi
+    else
+      OUTTIME=1990010100Z-2005123118Z ; export OUTTIME
+      ./disk_move_var
+      if [ $? -ne 0 ] ; then
+        echo "disk_move failed"
+        ./update_status error "$CASE $HIST $TPER"
+        exit 1
+      fi
+    fi
+  else
     ./disk_move_var
     if [ $? -ne 0 ] ; then
       echo "disk_move failed"
       ./update_status error "$CASE $HIST $TPER"
       exit 1
     else
-      OUTTIME=2071010100Z-2080123118Z ; export OUTTIME
-      ./disk_move_var
-      if [ $? -ne 0 ] ; then
-         echo "disk_move failed"
-        ./update_status error "$CASE $HIST $TPER"
-        exit 1
-      else
-        echo -n "TS disk_move end: " ; date
-      fi
-    fi
-  else
-    OUTTIME=1990010100Z-2005123118Z ; export OUTTIME
-    ./disk_move_var
-    if [ $? -ne 0 ] ; then
-      echo "disk_move failed"
-      ./update_status error "$CASE $HIST $TPER"
-      exit 1
+      echo -n "TS disk_move end: " ; date
     fi
   fi
-else
-  ./disk_move_var
-  if [ $? -ne 0 ] ; then
-    echo "disk_move failed"
-    ./update_status error "$CASE $HIST $TPER"
-    exit 1
-  else
-    echo -n "TS disk_move end: " ; date
-  fi
+  #
+  ./update_status complete
+  echo -n "TS COMPLETE: " ; date
 fi
 #
-./update_status complete
-echo -n "TS COMPLETE: " ; date
+exit
