minor changes to Omon

diff --git a/process_cmip5_template b/process_cmip5_template
--- a/process_cmip5_template
+++ b/process_cmip5_template
@@ -302,13 +302,13 @@ if [ ! -d $DISK_BASE ] ; then
 fi
 #
 cd $DISK_BASE
-#ln -s -f $BASEDIR/archive_var_read .
-#./archive_var_read $ARCHIVE_PROC $CCSM_VARS
-#if [ $? -ne 0 ] ; then
-#  echo "Error from archive_var_read"
-#  ./procstat.sh error archive_var_read
-#  exit 1
-#fi
+ln -s -f $BASEDIR/archive_var_read .
+./archive_var_read $ARCHIVE_PROC $CCSM_VARS
+if [ $? -ne 0 ] ; then
+  echo "Error from archive_var_read"
+  ./procstat.sh error archive_var_read
+  exit 1
+fi
 #
 # Run CMOR processor code
 #
