Porting to geyser in CISL

diff --git a/Process_Setup b/Process_Setup
--- a/Process_Setup
+++ b/Process_Setup
@@ -53,63 +53,33 @@ PROCHOST=`hostname`;export PROCHOST
 CCPS_SCRIPT=${CASE}_${HIST}_${TPER}_process.sh
 rm -f $CCPS_SCRIPT
 #
-if [ "$VARS" ] ; then
-  case "$PROCHOST" in 
-    silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | modeling1* | euclid* )  # NCAR and NERSC machines
-      echo "#!/bin/sh" > $CCPS_SCRIPT
-      cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                             | sed -e "s/xxxHISTxxx/$HIST/g" \
-                             | sed -e "s/xxxTPERxxx/$TPER/g" \
-                             | sed -e "s/xxxVARSxxx/$VARS/g" \
-                             >> $CCPS_SCRIPT ;;
-    mirage3 | mirage4 )
-      cat ./LSF_batch | sed -e "s/NAME/$CCPS_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CCPS_SCRIPT
-      cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                             | sed -e "s/xxxHISTxxx/$HIST/g" \
-                             | sed -e "s/xxxTPERxxx/$TPER/g" \
-                             | sed -e "s/xxxVARSxxx/$VARS/g" \
-                             >> $CCPS_SCRIPT ;;
-    lens* )                                  # lens @ ORNL
-      cat ./ORNL_batch > $CCPS_SCRIPT
-      cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                             | sed -e "s/xxxHISTxxx/$HIST/g" \
-                             | sed -e "s/xxxTPERxxx/$TPER/g" \
-                             | sed -e "s/xxxVARSxxx/$VARS/g" \
-                             >> $CCPS_SCRIPT ;;
-    * )
-      echo "Unable to build script because "$PROCHOST" unknown."
-      ./procstat.sh error process_template
-      exit 1 ;;
-  esac
-else
-  case "$PROCHOST" in 
-    silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | modeling1* | euclid* )  # NCAR and NERSC machines
-      echo "#!/bin/sh" > $CCPS_SCRIPT
-      cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                             | sed -e "s/xxxHISTxxx/$HIST/g" \
-                             | sed -e "s/xxxTPERxxx/$TPER/g" \
-                             | sed -e "s/xxxVARSxxx//g" \
-                             >> $CCPS_SCRIPT ;;
-    mirage3 | mirage4 )
-      cat ./LSF_batch | sed -e "s/NAME/$CCPS_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CCPS_SCRIPT
-      cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                             | sed -e "s/xxxHISTxxx/$HIST/g" \
-                             | sed -e "s/xxxTPERxxx/$TPER/g" \
-                             | sed -e "s/xxxVARSxxx//g" \
-                             >> $CCPS_SCRIPT ;;
-    lens* )                                  # lens @ ORNL
-      cat ./ORNL_batch > $CCPS_SCRIPT
-      cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
-                             | sed -e "s/xxxHISTxxx/$HIST/g" \
-                             | sed -e "s/xxxTPERxxx/$TPER/g" \
-                             | sed -e "s/xxxVARSxxx//g" \
-                             >> $CCPS_SCRIPT ;;
-    * )
-      echo "Unable to build script because "$PROCHOST" unknown."
-      ./procstat.sh error process_template
-      exit 1 ;;
-  esac
-fi
+case "$PROCHOST" in 
+  silver* | tramhill* | hurricane* | modeling1* | euclid* )  # NCAR and NERSC machines
+    echo "#!/bin/sh" > $CCPS_SCRIPT
+    cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
+                           | sed -e "s/xxxHISTxxx/$HIST/g" \
+                           | sed -e "s/xxxTPERxxx/$TPER/g" \
+                           | sed -e "s/xxxVARSxxx//g" \
+                           >> $CCPS_SCRIPT ;;
+  yslogin* )
+    cat ./NCAR_batch | sed -e "s/NAME/$CCPS_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CCPS_SCRIPT
+    cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
+                           | sed -e "s/xxxHISTxxx/$HIST/g" \
+                           | sed -e "s/xxxTPERxxx/$TPER/g" \
+                           | sed -e "s/xxxVARSxxx//g" \
+                           >> $CCPS_SCRIPT ;;
+  lens* )                                  # lens @ ORNL
+    cat ./ORNL_batch > $CCPS_SCRIPT
+    cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
+                           | sed -e "s/xxxHISTxxx/$HIST/g" \
+                           | sed -e "s/xxxTPERxxx/$TPER/g" \
+                           | sed -e "s/xxxVARSxxx//g" \
+                           >> $CCPS_SCRIPT ;;
+  * )
+    echo "Unable to build script because "$PROCHOST" unknown."
+    ./procstat.sh error process_template
+    exit 1 ;;
+esac
 #
 chmod +x $CCPS_SCRIPT
 echo ""
@@ -124,8 +94,8 @@ if [ "$DORUN" = "Y" ] ; then
   case "$PROCHOST" in
     lens* )
       ( /usr/bin/qsub ./${CCPS_SCRIPT} ) ;;
-    mirage3 | mirage4 )
-      ( /fs/local/apps/lsf/8.0/linux2.6-glibc2.3-x86_64/bin/bsub < ./${CCPS_SCRIPT} ) ;;
+    yslogin* )
+      ( /ncar/opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bsub < ./${CCPS_SCRIPT} ) ;;
     * )
       ( ./${CCPS_SCRIPT} > log.${CCPS_SCRIPT} 2>&1 & ) ;;
   esac
