Mods for LE5 and adding splitting of cice in hemispheres

diff --git a/Process_LE5 b/Process_LE5
--- a/Process_LE5
+++ b/Process_LE5
@@ -1,18 +1,36 @@
 #!/bin/sh
 #
-if [ $# -ne 4 ] ; then
-   echo "Usage: ./Process_LE5 CASE HIST TPER CENT"
-   echo "Four arguments REQUIRED:"
+if [ $# -ne 3 ] && [ $# -ne 4 ] ; then
+   echo "Usage: ./Process_LE5 CASE HIST TPER [CENT]"
+   echo "Three arguments REQUIRED:"
    echo "1: CASE name"
    echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h rtm.h0 etc]"
    echo "3: TPER time period of above HIST type - must be one of [ann mon day hr6 hr3 hr1 m30]"
+   echo ""
+   echo "One optional argument if CASE is an 1850 control-type run:"
    echo "4: CENT time period to process (1850 control only), e.g., 16 17 18 19 etc."
+   echo ""
    exit 1
 else
    CASE=$1 ; export CASE
    HIST=$2 ; export HIST
    TPER=$3 ; export TPER
-   CENT=$4 ; export CENT
+   if [ `echo $CASE | egrep "1850" | wc -c` -ne 0 ] ; then
+     if [ $# -ne 4 ] ; then
+       echo "Usage: ./Process_LE5 CASE HIST TPER CENT"
+       echo "Four arguments REQUIRED:"
+       echo "1: CASE name"
+       echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h rtm.h0 etc]"
+       echo "3: TPER time period of above HIST type - must be one of [ann mon day hr6 hr3 hr1 m30]"
+       echo "4: CENT time period to process (1850 control only), e.g., 16 17 18 19 etc."
+       echo ""
+       exit 1
+     else
+       CENT=$4 ; export CENT
+     fi
+   else
+     CENT="[0-9]" ; export CENT
+   fi
 fi
 #
 # Set up a bunch of stuff
