Shift from var_extract to slice2series

diff --git a/process_pac_template b/process_pac_template
--- a/process_pac_template
+++ b/process_pac_template
@@ -67,8 +67,6 @@ case "$PROCHOST" in
     exit 1 ;;
 esac
 #
-export LD_LIBRARY_PATH
-#
 # Strip off first part of $HIST
 #
 HTYP=`echo $HIST | cut -d'.' -f1` ; export HTYP
@@ -90,6 +88,9 @@ case "$HTYP" in
     echo "Unable to continue because "$HIST" not known."
     exit 1 ;;
 esac
+#
+# Set up local names and archival names
+#
 #
 # Set up local names and archival names
 #
@@ -134,7 +135,8 @@ VERBOSITY=3
 #
 # Array of all history (aka time-slice) files
 #
-SLICEFILES=(${LOCAL_PROC}/${CASE}.${HIST}.[0-9]*.nc) ; export SLICEFILES
+#SLICEFILES=(${LOCAL_PROC}/${CASE}.${HIST}.[0-9]*.nc) ; export SLICEFILES
+#echo "SLICEFILES 0: "${SLICEFILES[*]}
 #
 # Create output filename time period prefix
 #
@@ -144,9 +146,9 @@ PREFIX=${CACHEDIR}/to_archive/${CASE}.${HIST}.
 #
 case "$TPER" in
   mon )
-    SUFFIX=${YEARBEG}01-${YEAREND}12.nc ;;
+    SUFFIX=.${YEARBEG}01-${YEAREND}12.nc ;;
   day ) 
-    SUFFIX=${YEARBEG}0101-${YEAREND}1231.nc ;;
+    SUFFIX=.${YEARBEG}0101-${YEAREND}1231.nc ;;
 esac
 #
 # Print out values
@@ -195,7 +197,7 @@ cd
 ln -s -f ${BASEDIR}/run_slice2series     ${CACHEDIR}/run_slice2series
 ln -s -f ${BASEDIR}/store_to_archive_var ${CACHEDIR}/store_to_archive_var 
 ln -s -f ${BASEDIR}/archive_write_var    ${CACHEDIR}/archive_write_var    
-ln -s -f ${BASEDIR}/update_CACHEDIR      ${CACHEDIR}/update_status        
+ln -s -f ${BASEDIR}/update_status        ${CACHEDIR}/update_status        
 #
 # Start actual processing, extract each field one at a time for all times
 #
@@ -248,17 +250,17 @@ echo -n "TS run_slice2series end   : " ; date
 #
 # Store completed data on archival system
 #
-#echo -n "TS archive start: " ; date
-#./store_to_archive_var
-#if [ $? -ne 0 ] ; then
-#  echo "store_to_archive failed"
-#  ./update_status error "$CASE $HIST $TPER"
-#  exit 1
-#else
-#  echo -n "TS archive end: " ; date
-#fi
-##
-#./update_status complete
-#echo -n "TS COMPLETE: " ; date
+echo -n "TS archive start: " ; date
+./store_to_archive_var
+if [ $? -ne 0 ] ; then
+  echo "store_to_archive failed"
+  ./update_status error "$CASE $HIST $TPER"
+  exit 1
+else
+  echo -n "TS archive end: " ; date
+fi
+#
+./update_status complete
+echo -n "TS COMPLETE: " ; date
 #
 exit
