Modifications for pop in process_lme_template

diff --git a/process_lme_template b/process_lme_template
--- a/process_lme_template
+++ b/process_lme_template
@@ -227,33 +227,33 @@ if [ "$HIST" = "pop.h" ] || [ "$HIST" = "pop.h.nday1" ] ; then
         exit 1
       fi
       echo -n "TS var_extract end  : " ; date
-    done
 #
 # Store completed data on archival system
 #
-    echo -n "TS archive start: " ; date
-    ./store_to_archive_var
-    if [ $? -ne 0 ] ; then
-      echo "store_to_archive failed"
-      ./update_status error "$CASE $HIST $TPER"
-      exit 1
-    else
-      echo -n "TS archive end: " ; date
-    fi
+      echo -n "TS archive start: " ; date
+      ./store_to_archive_var
+      if [ $? -ne 0 ] ; then
+        echo "store_to_archive failed"
+        ./update_status error "$CASE $HIST $TPER"
+        exit 1
+      else
+        echo -n "TS archive end: " ; date
+      fi
 #
 # Move completed data on to DISK_PROC
 #
-    echo -n "TS disk move start: " ; date
-    ./disk_move_var
-    if [ $? -ne 0 ] ; then
-      echo "disk_move_var failed"
-      ./update_status error "$CASE $HIST $TPER"
-      exit 1
-    else
-      echo -n "TS disk_move_var end: " ; date
+      echo -n "TS disk move start: " ; date
+      ./disk_move_var
+      if [ $? -ne 0 ] ; then
+        echo "disk_move_var failed"
+        ./update_status error "$CASE $HIST $TPER"
+        exit 1
+      else
+        echo -n "TS disk_move_var end: " ; date
+      fi
+      touch .comp.${CASE}.${HIST}.${ICEN}
     fi
-    touch .comp.${CASE}.${HIST}.${ICEN}
-  fi
+  done
 #
 # All other output streams
 #
