Added status check to store_to_archive_var for HPSS write fail

diff --git a/store_to_archive_var b/store_to_archive_var
--- a/store_to_archive_var
+++ b/store_to_archive_var
@@ -20,6 +20,11 @@ cd $CACHEDIR
 #
 if [ `/bin/ls ${CASE}.${HIST}.*.${OUTTIME}.nc | wc -l` -ne 0 ] ; then
   ../archive_write_var
+  if [ $? -ne 0 ] ; then
+    echo "archive_write_var failed"
+    ./update_status error archive_write_var
+    exit 1
+  fi
 else
   echo "No files in "$CACHEDIR". Exit."
 fi
