Additional changes for GeoMIP

diff --git a/CMOR2/Run6hrPlev b/CMOR2/Run6hrPlev
--- a/CMOR2/Run6hrPlev
+++ b/CMOR2/Run6hrPlev
@@ -32,6 +32,7 @@ fi
 #
 BASED=${HOME}/CCP_Processing_Suite
 CMORD=${HOME}/CCP_Processing_Suite/CMOR2
+CBIND=${HOME}/bin
 #
 XWALK=xwalk_6hrPlev.txt
 #
@@ -71,6 +72,7 @@ echo $COMP >> 6hrPlev_in.${CASE}.${COMP}
 #
 WHOAMI=`whoami`
 PRCHST=`hostname`
+SVNBIN=`which svn`
 SVNREV=`$SVNBIN info $SVN | egrep "Rev:"`
 SVNDAT=`$SVNBIN info $SVN | egrep "Date:"`
 SVNUID=`$SVNBIN info $SVN | egrep "UUID:"`
@@ -79,6 +81,14 @@ echo $PRCHST >> Info_in.${CASE}.${COMP}
 echo $SVNREV >> Info_in.${CASE}.${COMP}
 echo $SVNDAT >> Info_in.${CASE}.${COMP}
 echo $SVNUID >> Info_in.${CASE}.${COMP}
-cat 6hrPlev_in.${CASE}.${COMP} | 6hrPlev_CMOR
+#
+if [ -f ${CBIND}/6hrPlev_CMOR ] ; then
+  ln -s -f ${CBIND}/6hrPlev_CMOR .
+else
+  echo "6hrPlev_CMOR NOT FOUND in "${CBIND}". Rebuild."
+  exit 1
+fi
+#
+cat 6hrPlev_in.${CASE}.${COMP} | ./6hrPlev_CMOR
 #
 #rm -f 6hrPlev_in.${CASE}.${COMP}
diff --git a/CMOR2/RunAmon b/CMOR2/RunAmon
--- a/CMOR2/RunAmon
+++ b/CMOR2/RunAmon
@@ -30,6 +30,7 @@ else
    echo '   ./RunAmon b40.20th.track1.deg.008 cam2.h0 "tas ta pr"'
 fi
 #
+CBIND=${HOME}/bin
 BASED=${HOME}/CCP_Processing_Suite
 CMORD=${HOME}/CCP_Processing_Suite/CMOR2
 #
@@ -88,6 +89,14 @@ echo $PRCHST >> Info_in.${CASE}.${COMP}
 echo $SVNREV >> Info_in.${CASE}.${COMP}
 echo $SVNDAT >> Info_in.${CASE}.${COMP}
 echo $SVNUID >> Info_in.${CASE}.${COMP}
-cat Amon_in.${CASE}.${COMP} | Amon_CMOR
+#
+if [ -f ${CBIND}/Amon_CMOR ] ; then
+  ln -s -f ${CBIND}/Amon_CMOR .
+else
+  echo "Amon_CMOR NOT FOUND in "${CBIND}". Rebuild."
+  exit 1
+fi
+#
+cat Amon_in.${CASE}.${COMP} | ./Amon_CMOR
 #
 #rm -f Amon_in.${CASE}.${COMP}
diff --git a/CMOR2/RunLImon b/CMOR2/RunLImon
--- a/CMOR2/RunLImon
+++ b/CMOR2/RunLImon
@@ -73,6 +73,7 @@ echo $COMP >> LImon_in.${CASE}.${COMP}
 #
 WHOAMI=`whoami`
 PRCHST=`hostname`
+SVNBIN=`which svn`
 SVNREV=`$SVNBIN info $SVN | egrep "Rev:"`
 SVNDAT=`$SVNBIN info $SVN | egrep "Date:"`
 SVNUID=`$SVNBIN info $SVN | egrep "UUID:"`
@@ -81,6 +82,15 @@ echo $PRCHST >> Info_in.${CASE}.${COMP}
 echo $SVNREV >> Info_in.${CASE}.${COMP}
 echo $SVNDAT >> Info_in.${CASE}.${COMP}
 echo $SVNUID >> Info_in.${CASE}.${COMP}
-cat LImon_in.${CASE}.${COMP} | LImon_CMOR
+#
+CBIND=${HOME}/bin
+if [ -f ${CBIND}/LImon_CMOR ] ; then
+  ln -s -f ${CBIND}/LImon_CMOR .
+else
+  echo "LImon_CMOR NOT FOUND in "${CBIND}". Rebuild."
+  exit 1
+fi
+#
+cat LImon_in.${CASE}.${COMP} | ./LImon_CMOR
 #
 #rm -f LImon_in.${CASE}.${COMP}
diff --git a/CMOR2/RunOmon b/CMOR2/RunOmon
--- a/CMOR2/RunOmon
+++ b/CMOR2/RunOmon
@@ -34,6 +34,7 @@ LD_LIBRARY_PATH=/usr/local/netcdf-4.1.3-pgi-hpf-cc-11.5-0/lib:/usr/lib64/mpich2/
 #
 BASED=${HOME}/CCP_Processing_Suite
 CMORD=${HOME}/CCP_Processing_Suite/CMOR2
+CBIND=${HOME}/bin
 #
 XWALK=xwalk_Omon.txt
 #
@@ -84,6 +85,14 @@ echo $PRCHST >> Info_in.${CASE}.${COMP}
 echo $SVNREV >> Info_in.${CASE}.${COMP}
 echo $SVNDAT >> Info_in.${CASE}.${COMP}
 echo $SVNUID >> Info_in.${CASE}.${COMP}
-cat Omon_in.${CASE}.${COMP} | Omon_CMOR
+#
+if [ -f ${CBIND}/Omon_CMOR ] ; then
+  ln -s -f ${CBIND}/Omon_CMOR .
+else
+  echo "Omon_CMOR NOT FOUND in "${CBIND}". Rebuild."
+  exit 1
+fi
+#
+cat Omon_in.${CASE}.${COMP} | ./Omon_CMOR
 #
 #rm -f Omon_in.${CASE}.${COMP}
diff --git a/CMOR2/Runfx b/CMOR2/Runfx
--- a/CMOR2/Runfx
+++ b/CMOR2/Runfx
@@ -15,6 +15,7 @@ fi
 #
 BASED=${HOME}/CCP_Processing_Suite
 CMORD=${HOME}/CCP_Processing_Suite/CMOR2
+CBIND=${HOME}/bin
 #
 XWALK=xwalk_fx.txt
 #
@@ -52,6 +53,7 @@ fi
 #
 WHOAMI=`whoami`
 PRCHST=`hostname`
+SVNBIN=`which svn`
 SVNREV=`$SVNBIN info $SVN | egrep "Rev:"`
 SVNDAT=`$SVNBIN info $SVN | egrep "Date:"`
 SVNUID=`$SVNBIN info $SVN | egrep "UUID:"`
@@ -60,5 +62,12 @@ echo $PRCHST >> Info_in.fx
 echo $SVNREV >> Info_in.fx
 echo $SVNDAT >> Info_in.fx
 echo $SVNUID >> Info_in.fx
-fx_CMOR
 #
+if [ -f ${CBIND}/fx_CMOR ] ; then
+  ln -s -f ${CBIND}/fx_CMOR .
+else
+  echo "fx_CMOR NOT FOUND in "${CBIND}". Rebuild."
+  exit 1
+fi
+#
+./fx_CMOR
